docs/reference/custom-resource-application.md
SC: https://app.shortcut.com/replicated/story/44019/content-diff-remove-minkotsversion-limitations
https://deploy-preview-182--replicated-docs.netlify.app/reference/custom-resource-application#minkotsversion-beta
=> 44019 content diff for minkotsversion

README.md
SC: https://app.shortcut.com/replicated/story/44084/updated-the-replicated-docs-readme-after-the-repo-is-public
=> 44084: Update README.md

docs/reference/custom-resource-application.md
SC: https://app.shortcut.com/replicated/story/44020/content-diff-update-intro-and-minimum-kots-versions
https://deploy-preview-188--replicated-docs.netlify.app/reference/custom-resource-application#targetkotsversion
=> 44020 content diff

docs/reference/kots-cli-upstream-download.md, docs/reference/kots-cli-upstream-upgrade.md, docs/reference/kots-cli-upstream.md, docs/release-notes/rn-app-manager.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/44106/friday-3-4-migrate-one-month-of-kots-release-notes-content-and-update-links
Preview: https://deploy-preview-187--replicated-docs.netlify.app/release-notes/rn-app-manager
=> 44106: Migrated the latest month of KOTS Release Notes

docs/release-notes/rn-kubernetes-installer.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/44107/friday-3-4-migrate-one-month-of-kurl-release-notes-content-and-update-links
https://deploy-preview-189--replicated-docs.netlify.app/release-notes/rn-kubernetes-installer
=> adds one month of kurl rns

docs/reference/kots-cli-global-flags.md
SC: https://app.shortcut.com/replicated/story/44026/rebrand-the-kots-cli-documentation
https://deploy-preview-192--replicated-docs.netlify.app/reference/kots-cli-global-flags
=> 44026 replaces KOTS with kots CLI

docs/reference/kots-cli-get-versions.md, docs/reference/kots-cli-set-index.md
SC: https://app.shortcut.com/replicated/story/44022/content-diff-fix-typo
=> 44022 content diff fix typos

docs/vendor/licenses-adding-custom-fields.md
SC: https://app.shortcut.com/replicated/story/44047/review-and-edit-delete-license-fields-pr
Updates to the Updating and Deleting sections from Grant's PR: https://deploy-preview-193--replicated-docs.netlify.app/vendor/licenses-adding-custom-fields
=> 44047 Edits for clarity and style to the update/delete license fields procedures

docs/reference/template-functions-identity-context.md
SC: https://app.shortcut.com/replicated/story/44394/content-diff-change-api-for-ingress
Previews:
- https://deploy-preview-196--replicated-docs.netlify.app/reference/template-functions-identity-context#identityservicename
- https://deploy-preview-196--replicated-docs.netlify.app/reference/template-functions-identity-context#identityserviceport
=> 44394: Update template-functions-identity-context.md

docs/enterprise/image-registry-embedded-cluster.md
SC: https://app.shortcut.com/replicated/story/44396/content-diff-fix-image-garbage-collection-patch-command
Preview: https://deploy-preview-198--replicated-docs.netlify.app/enterprise/image-registry-embedded-cluster#enable-and-disable-image-garbage-collection
=> 44396: Fix image garbage collection patch command

docs/reference/custom-resource-config.md
And added the text input to the configuration docs and correctly ordered the examples.
=> Added the text input config option

docs/release-notes/rn-app-manager.md
SC: https://app.shortcut.com/replicated/story/44519/fix-statement-in-app-manager-release-notes
Preview: https://deploy-preview-201--replicated-docs.netlify.app/release-notes/rn-app-manager
=> 44519: Update rn-app-manager.md

docs/enterprise/installing-existing-cluster-online.md
Reverts replicatedhq/replicated-docs#207
=> Revert "add Strict preflight Checks docs"

docs/vendor/policies-support-lifecycle.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/44621/new-support-policy-page
Preview: https://deploy-preview-211--replicated-docs.netlify.app/vendor/policies-support-lifecycle
=> 44621 adds support lifecycle policy page

README.md
SC: https://app.shortcut.com/replicated/story/44478/replicated-docs-readme-add-guidance-for-folders-and-sidebar-js
=> 44478: Update README.md

docs/vendor/policies-support-lifecycle.md
SC: https://app.shortcut.com/replicated/story/44638/edit-support-policy-table-spacing
=> 44638 edit support policy tables

README.md
SC: https://app.shortcut.com/replicated/story/44478/replicated-docs-readme-add-guidance-for-folders-and-sidebar-js
Some corrections to the table formatting and other tweaks.
=> 44478-B: Update README.md

README.md
SC: https://app.shortcut.com/replicated/story/44478/replicated-docs-readme-add-guidance-for-folders-and-sidebar-js
=> 44478-C: Fixed table, other minor edits

docs/vendor/team-management-saml-auth.md, docs/vendor/team-management.md
not yet ready for deploy... should be on Monday
=> hold: prep for saml accont conflict

README.md
SC: https://app.shortcut.com/replicated/story/44757/readme-fix-table-and-add-a-toc
Quick fix on the Note style.
=> 44757-B: Update README.md

docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/44831/migrate-the-remaining-kurl-release-notes
https://deploy-preview-227--replicated-docs.netlify.app/release-notes/rn-kubernetes-installer
=> Copies all kURL release notes

docs/release-notes/rn-app-manager.md
SC: https://app.shortcut.com/replicated/story/44775/migrate-the-remaining-kots-release-notes
Preview this date and older: https://deploy-preview-229--replicated-docs.netlify.app/release-notes/rn-app-manager#1593
=> 44775: Migrated more KOTS/app manager release notes

docs/release-notes/rn-app-manager.md
https://app.shortcut.com/replicated/story/45089/forgot-to-delete-app-manager-rn-note
=> delete note in app manager rns

docs/templates/release-notes.md
SC: https://app.shortcut.com/replicated/story/44401/make-a-release-notes-template
Added to template folder
=> 44401 adds rn template

docs/vendor/releases-promoting.md
SC: https://app.shortcut.com/replicated/story/45361/remove-inaccurate-info-in-promoting-releases-topic
Background: https://replicated.slack.com/archives/C02BPJQQP28/p1647980335218649?thread_ts=1647899841.053439&cid=C02BPJQQP28
=> 45361 removes out of date field

docs/reference/custom-resource-about.md
Corrects version numbers on troubleshoot CRs: https://app.shortcut.com/replicated/story/45389/change-beta1-to-beta2-for-troubleshoot-crs-in-custom-resource-topic
=> 45389 update troubleshoot CRs to v1beta2

docs/release-notes/rn-kubernetes-installer.md
Preview: https://deploy-preview-253--replicated-docs.netlify.app/release-notes/rn-kubernetes-installer
=> Update kURL Release Notes

docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/45415/fix-link-in-kurl-release-notes
=> 45415: Fix link in kurl RN

docs/reference/replicated-cli-release-promote.md
https://app.shortcut.com/replicated/story/45256/document-the-ability-to-make-an-app-version-required
=> 45256 removes outdated flag and formatting updates

docs/enterprise/updating-apps.md
SC: https://app.shortcut.com/replicated/story/45432/formatting-error-in-updating-applications-topic
Addressed markdown formatting error and conflicting content with the strict preflight check note.
Looks like the netlify checks aren't showing up, so here's the preview: https://623caaece18f7b0008750cd7--replicated-docs.netlify.app/enterprise/updating-apps
=> 45432 fixes markdown formatting issues

docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/45456/broken-links
=> 45456 fixes broken links

docs/vendor/team-management-saml-auth.md
SC: https://app.shortcut.com/replicated/story/45891/fix-typo-in-saml-auth-team-management
Preview: https://deploy-preview-268--replicated-docs.netlify.app/vendor/team-management-saml-auth
=> 45891: Fix typos

docs/reference/replicated-cli-release-promote.md
SC: https://app.shortcut.com/replicated/story/45256/document-the-ability-to-make-an-app-version-required
CLI doc update for the required releases feature.
=> [1.68.0] WAIT UNTIL RELEASE TO MERGE 45256 adds --required flag

docs/vendor/packaging-private-images.md
https://app.shortcut.com/replicated/story/45984/incorporate-docs-feedback-on-private-image-registries-topic
Addressed your feedback from https://github.com/replicatedhq/replicated-docs/pull/256
Preview: https://deploy-preview-276--replicated-docs.netlify.app/vendor/packaging-private-images
=> 45984 Typo edits

docs/vendor/licenses-about-types.md
Related to https://app.shortcut.com/replicated/story/46047/orange-team-support-changing-a-license
=> Fixes typo

docs/reference/custom-resource-identity.md
SC: https://app.shortcut.com/replicated/story/46172/mark-this-topic-as-beta-identity-cr
Preview: https://deploy-preview-281--replicated-docs.netlify.app/reference/custom-resource-identity
=> 46172: Added Beta label

docs/templates/procedure.md
SC: https://app.shortcut.com/replicated/story/46247/updated-procedure-template-with-html-table-style
=> 46247: Update procedure.md

docs/vendor/licenses-about-types.md
SC: https://app.shortcut.com/replicated/story/46047/orange-team-support-changing-a-license
Preview: https://deploy-preview-279--replicated-docs.netlify.app/vendor/licenses-about-types#community-licenses
Related enterprise user content: https://github.com/replicatedhq/replicated-docs/pull/278
=> Do Not Merge - Blocked on Release - 46047 changing community licenses

docs/enterprise/updating-licenses.md
SC: https://app.shortcut.com/replicated/story/46047/orange-team-support-changing-a-license
Preview: https://deploy-preview-278--replicated-docs.netlify.app/enterprise/updating-licenses#changing-a-community-license
Related vendor content added in this PR: https://github.com/replicatedhq/replicated-docs/pull/279
=> Do Not Merge - Blocked on Release - 46047 Changing Community License

docs/vendor/packaging-kots-versions.md
SC: https://app.shortcut.com/replicated/story/45951/take-a-quick-looks-at-alex-s-last-edits-and-see-if-they-re-worth-pulling-in
Preview: https://deploy-preview-293--replicated-docs.netlify.app/vendor/packaging-kots-versions
=> 45951: Edits from Alex

docs/vendor/tutorial-installing-air-gap-existing-cluster-gcp.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/44181/airgap-existing-cluster-guide-updates
Preview: https://deploy-preview-294--replicated-docs.netlify.app/vendor/tutorial-installing-air-gap-existing-cluster-gcp
=> 44181: Changed location in TOC

docs/reference/template-functions-kurl-context.md
SC: https://app.shortcut.com/replicated/story/44514/documentation-examples-use-unicode-quotes
Preview: https://deploy-preview-310--replicated-docs.netlify.app/reference/template-functions-kurl-context
=> 44514 replace unicode quotes with ascii

docs/vendor/packaging-embedded-kubernetes.md
SC: https://app.shortcut.com/replicated/story/42264/content-gap-provide-more-guidance-to-readers-on-how-to-actually-pin-versions-in-kurl-existing-content-available
https://deploy-preview-309--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes
=> 42264 add link for pinning versions

docs/templates/procedure.md, docs/vendor/team-management-rbac-resource-names.md, docs/vendor/team-management-vendor-rbac.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/45471/add-rbac-info-to-the-vendor-docs
Previews:
- https://deploy-preview-283--replicated-docs.netlify.app/vendor/team-management-vendor-rbac
- https://deploy-preview-283--replicated-docs.netlify.app/vendor/team-management-rbac-resource-names
=> 45471: Copy RBAC from help.replicated site

docs/vendor/team-management-rbac-resource-names.md
Saw this as I was reading the new RBAC page
=> Fix size to match

docs/vendor/packaging-air-gap-excluding-minio.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/46021/blue-team-provide-kotsadm-airgap-bundle
Preview: https://deploy-preview-312--replicated-docs.netlify.app/vendor/packaging-air-gap-excluding-minio
=> HOLD ON RELEASE - 46021: Exclude MinIO from air gap bundles

docs/vendor/support-submit-request.md
SC: https://app.shortcut.com/replicated/story/47060/change-results-step-in-submitting-a-support-request
https://deploy-preview-325--replicated-docs.netlify.app/vendor/support-submit-request
=> 47060: Correction to support issue creation behavior

docs/enterprise/snapshots-understanding.md
https://app.shortcut.com/replicated/story/47137/typo-in-snapshots-docs
=> 47137 typo fix

docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-restoring-partial.md, docs/enterprise/snapshots-storage-destinations.md, docs/enterprise/snapshots-troubleshooting-backup-restore.md, docs/reference/custom-resource-about.md, docs/reference/custom-resource-backup.md, docs/vendor/snapshots-backup-hooks.md, docs/vendor/snapshots-overview.md
https://app.shortcut.com/replicated/story/46907/update-velero-docs-links-that-point-to-the-netlify-preview-site
=> 46907 update velero docs links

docs/vendor/packaging-private-images.md
https://app.shortcut.com/replicated/story/46676/add-tutorial-as-additional-resource-to-private-registries-topic
https://deploy-preview-333--replicated-docs.netlify.app/vendor/packaging-private-images
=> 46676 add links to ecr tutorial

docs/vendor/packaging-private-images.md
https://app.shortcut.com/replicated/story/46679/clarify-that-for-aws-you-need-to-create-a-service-account-user-for-connecting-to-private-registry
https://deploy-preview-334--replicated-docs.netlify.app/vendor/packaging-private-images
=> 46679 add ecr registry details

docs/reference/template-functions-static-context.md
https://github.com/replicatedhq/kots/pull/2746
=> WAIT FOR RELEASE 45383 Document YamlEscape function

docs/enterprise/auth-changing-passwords.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/46758/blue-team-change-password-in-admin-console-ui
Preview: https://deploy-preview-326--replicated-docs.netlify.app/enterprise/auth-changing-passwords
=> HOLD ON RELEASE: 46758: Change Password in Admin Console

docs/reference/kots-cli-install.md
assoicated PR in kots https://github.com/replicatedhq/kots/pull/2719
=> docs change for new flag in kots install

docs/reference/custom-resource-helmchart.md, docs/vendor/helm-native-helm-install-order.md
Helm install order how-to doc: https://deploy-preview-332--replicated-docs.netlify.app/vendor/helm-native-helm-install-order
HelmChart reference: https://deploy-preview-332--replicated-docs.netlify.app/reference/custom-resource-helmchart#weight
https://app.shortcut.com/replicated/story/46581/blue-team-document-helm-chart-install-order
=> WAIT FOR RELEASE 46581 add install order docs

docs/release-notes/rn-kubernetes-installer.md
release notes for kURL v2022.05.06-0
=> V2022.05.06 0 release notes

docs/release-notes/rn-app-manager.md
quick one @jonquil2002 when you have a moment
=> clarify that it's a PDF, not a file in github

docs/release-notes/rn-kubernetes-installer.md
https://app.shortcut.com/replicated/story/48433/link-to-aws-add-on-docs-missing-from-rn
https://deploy-preview-357--replicated-docs.netlify.app/release-notes/rn-kubernetes-installer#release-v20220510-0
=> 48433 add link for more info

docs/enterprise/snapshots-storage-destinations.md
https://app.shortcut.com/replicated/story/47794/document-what-s3-compatible-backends-are-supported
Updated the content at the top: https://deploy-preview-360--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations
and the S3-Compatible section: https://deploy-preview-360--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations#s3-compatible
=> 47794 clarify which are the supported s3-compat object stores

docs/reference/custom-resource-helmchart.md, docs/vendor/helm-installing-replicated-helm.md, docs/vendor/helm-overview.md, docs/vendor/helm-release.md, sidebars.js
**This PR changes a filename and requires a redirect before it can be merged.** Redirect story for SRE team: https://app.shortcut.com/replicated/story/48726/redirect-for-helm-docs
Shortcut: https://app.shortcut.com/replicated/story/48533/better-document-how-vendors-add-helm-charts-to-a-release
Preview: https://deploy-preview-361--replicated-docs.netlify.app/vendor/helm-release
For reference, here's the old topic that this replaces: https://docs.replicated.com/vendor/helm-installing-replicated-helm
=> 48533 How to add a helm chart to a release

docs/enterprise/gitops-workflow.md
SC: https://app.shortcut.com/replicated/story/42804/gitops-workflow-topic-is-incorrect
Preview: https://deploy-preview-359--replicated-docs.netlify.app/enterprise/gitops-workflow
=> 42804: Update gitops-workflow.md

docs/vendor/packaging-ingress.md
SC: https://app.shortcut.com/replicated/story/48502/move-configuring-cluster-ingress-to-the-mapping-values-topic
=> 48502-NEW: Changed title to Adding Cluster Ingress Options

docs/release-notes/rn-app-manager.md, docs/release-notes/rn-kubernetes-installer.md
This reverts commit fc069beba7bc5cdb551b45d085cffd2f0f1be5c8, reversing
changes made to 49993182aed5a580125a51b1f15241ace86daf7c.
=> Add back release notes

docs/templates/procedure.md, docs/vendor/packaging-embedded-kubernetes.md
SC: https://app.shortcut.com/replicated/story/49002/orange-team-kubernetes-installer-improvements-iteration-1
Preview: https://deploy-preview-376--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes
=> Wait for Release - 49002: Add Kubernetes Installer to a Release

docs/enterprise/auth-changing-passwords.md
Story: https://app.shortcut.com/replicated/story/49605/document-where-we-store-the-admin-console-password
Preview: https://deploy-preview-390--replicated-docs.netlify.app/enterprise/auth-changing-passwords
=> 49605 Explain where/how adm password is stored

docs/enterprise/delete-admin-console.md, docs/enterprise/uninstall-admin-console.md, sidebars.js
Story: https://app.shortcut.com/replicated/story/39251/deleting-only-the-kots-components
~~https://deploy-preview-395--replicated-docs.netlify.app/enterprise/uninstall-admin-console~~
New: https://deploy-preview-395--replicated-docs.netlify.app/enterprise/delete-admin-console
=> 39251 add new uninstalling doc

docs/enterprise/auth-changing-passwords.md, docs/reference/kots-cli-remove.md
Story: https://app.shortcut.com/replicated/story/49942/blue-team-changes-to-the-admin-console-nav-bar
- Updated step 2: https://deploy-preview-391--replicated-docs.netlify.app/enterprise/auth-changing-passwords
- Rather than editing, I just removed mention of how you can install multiple apps with the admin console or cli because it didn't seem super relevant to this topic: https://deploy-preview-391--replicated-docs.netlify.app/reference/kots-cli-remove
=> Wait For Release: 49942 updates based on changes to adm nav bar

docs/reference/template-functions-static-context.md
https://app.shortcut.com/replicated/story/50882/update-the-static-context-docs-with-full-list-of-distros
Preview: https://deploy-preview-409--replicated-docs.netlify.app/reference/template-functions-static-context#distribution
=> 50882 add list of distribution return values

docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-restoring-partial.md, docs/enterprise/snapshots-storage-destinations.md, docs/reference/custom-resource-about.md, docs/reference/custom-resource-backup.md, docs/vendor/snapshots-backup-hooks.md, docs/vendor/snapshots-overview.md
https://app.shortcut.com/replicated/story/50566/update-velero-links-to-latest-version
=> 50566 update velero links

docs/enterprise/installing-embedded-cluster.md
SC: https://app.shortcut.com/replicated/story/47495/style-procedure-improvements-to-installing-with-the-kubernetes-installer
Preview: https://deploy-preview-381--replicated-docs.netlify.app/enterprise/installing-embedded-cluster
=> 47495: Update Enterprise Installing an Embedded Cluster

docs/vendor/packaging-embedded-kubernetes.md, docs/vendor/snapshots-configuring-backups.md, docs/vendor/snapshots-overview.md
SC: https://app.shortcut.com/replicated/story/38776/snapshots-add-on-for-embedded-cluster-can-be-included-in-kubenetes-installer-spec
Previews:
- https://deploy-preview-415--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes
- https://deploy-preview-415--replicated-docs.netlify.app/vendor/snapshots-overview
=> 38776: Benefits of including Velero add-on with Kubernetes installer

docs/enterprise/installing-embedded-cluster.md, docs/enterprise/installing-general-requirements.md, docs/enterprise/installing-overview.md
Edits from peer review of https://github.com/replicatedhq/replicated-docs/pull/413
Story: https://app.shortcut.com/replicated/story/27197/discover-and-document-cpu-memory-and-disk-needs-of-kots-so-we-can-correctly-convey-the-necessary-footprint-of-kots-to-vendors
=> Edits to #413

docs/vendor/admin-console-prometheus-monitoring.md
https://app.shortcut.com/replicated/story/40129/when-graphs-is-modified-in-the-kots-application-spec-the-default-graphs-go-away
Preview: https://deploy-preview-417--replicated-docs.netlify.app/vendor/admin-console-prometheus-monitoring
=> 40129 Explain how to modify default graphs

docs/vendor/packaging-embedded-kubernetes.md
Supporting docs for: https://github.com/replicatedhq/kots/pull/2925
=> docs: installer preflight check

docs/vendor/team-management-saml-auth.md
do we want a period at the end of that sentence? Unsure where it should go so I removed it 🙂 will defer to y'all on that part
=> add missing paren

docs/release-notes/rn-kubernetes-installer.md
was able to get an extra improvement in in the kURL release regarding a CVE fix/improvement
=> cve release notes

docs/templates/procedure.md, docs/templates/process-multiple-procedures.md, docs/vendor/packaging-planning-checklist.md, docs/vendor/packaging-private-images.md, docs/vendor/releases-creating-channels.md, docs/vendor/releases-creating-customer.md, docs/vendor/releases-creating-releases.md, docs/vendor/releases-promoting.md, docs/vendor/releases-sharing-license-install-script.md, docs/vendor/releases-updating.md, docs/vendor/repository-workflow-and-tagging-releases.md, docs/vendor/snapshots-configuring-backups.md, docs/vendor/team-management-google-auth.md, docs/vendor/team-management-rbac-about.md, docs/vendor/tutorial-ecr-private-images.md
SC: https://app.shortcut.com/replicated/story/52656/make-updates-to-github-topic-templates
- Updated the topic templates with the style guide decision for using bulleted lists for "Replace with" placeholder text definitions
- Updated the topic templates with the style guide decision for "Related Topics"
- Changed "Additional Resources" to "Related Topic" or Related Topics" in user-facing topics using silver search.
=> 52656: Procedure templates and Related Topic changes

docs/enterprise/installing-general-requirements.md
https://app.shortcut.com/replicated/story/53507/add-openshift-version-compatibility-info-to-install-reqs
Preview (see OpenShift version compatibility bullet): https://deploy-preview-470--replicated-docs.netlify.app/enterprise/installing-general-requirements#existing-cluster-requirements
=> adds openshift req

docs/reference/kots-cli-admin-console-generate-manifests.md
https://app.shortcut.com/replicated/story/53689/edit-https-github-com-replicatedhq-replicated-docs-pull-468
=> style edits on #468

docs/vendor/support-submit-request.md
SC: https://app.shortcut.com/replicated/story/53386/vendor-portal-add-support-bundle-guidance-for-47418
Preview: https://deploy-preview-469--replicated-docs.netlify.app/vendor/support-submit-request
=> 53386: Update support-submit-request.md

docs/vendor/tutorial-installing-without-existing-cluster.md
https://replicated.slack.com/archives/C02BPJQQP28/p1659022207696819
Preview: https://deploy-preview-492--replicated-docs.netlify.app/vendor/tutorial-installing-without-existing-cluster#install-the-application
=> edit url and password steps for clarify

docs/enterprise/monitoring-applications.md
https://app.shortcut.com/replicated/story/54799/typo-fix
=> Fixes "Altering" typo

docs/enterprise/snapshots-storage-destinations.md, docs/enterprise/snapshots-troubleshooting-backup-restore.md
https://app.shortcut.com/replicated/story/54089/document-workaround-for-increasing-the-memory-limit-of-restic-pod
Previews:
- See the second "Replicated recommends that you..." prerequisite https://deploy-preview-496--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations#prerequisites
- New "Memory Limit" troubleshooting section: https://deploy-preview-496--replicated-docs.netlify.app/enterprise/snapshots-troubleshooting-backup-restore#memory-limit-reached-on-the-restic-pod
=> Adds info on increasing restic memory limit

docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/55436/edit-kubernetes-installer-release-notes
=> 54436: Edits to Kubernetes Installer RN for style/wording changes.

docs/reference/custom-resource-helmchart.md, docs/vendor/helm-processing.md
Reverts replicatedhq/replicated-docs#513
=> Revert "Default to Helm v3"

docs/vendor/packaging-private-registry-cname.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/50499/document-ability-to-add-custom-cname-for-replicated-private-registry-proxy
Preview: https://deploy-preview-407--replicated-docs.netlify.app/vendor/packaging-private-registry-cname
=> 50499: Using CNAME Records with Private Registries

docs/reference/custom-resource-helmchart.md, docs/vendor/helm-processing.md
Reverts replicatedhq/replicated-docs#516
Don't merge until the next KOTS release
=> Default to Helm v3

docs/release-notes/rn-kubernetes-installer.md
also fixes a typo that I noticed in the last kotsadm add-on release note.
=> kurl release notes v2022.08.12-1

docs/reference/custom-resource-redactor.md
SC: https://app.shortcut.com/replicated/story/53217/better-reference-content-on-redactor-custom-resources
Preview: https://deploy-preview-507--replicated-docs.netlify.app/reference/custom-resource-redactor
=> 53217: Improve Redactor Custom Resource Content

docs/vendor/namespaces.md
Based on this question https://community.replicated.com/t/how-to-reuse-tls-certificate-from-another-namespace/918/2
=> Clarify Namespace guidance

docs/vendor/helm-install.md, docs/vendor/packaging-private-registry-cname.md
Renames the topic title and updates a xref accordinly. (Does not update xrefs from old release notes)
Story: https://app.shortcut.com/replicated/story/52753/change-using-helm-to-install-title
Preview: https://deploy-preview-539--replicated-docs.netlify.app/vendor/helm-install
=> Renames helm install alpha topic

docs/enterprise/snapshots-understanding.md, docs/vendor/snapshots-overview.md
SC: https://app.shortcut.com/replicated/story/31553/docs-better-document-the-detail-of-what-a-full-snapshot-backs-up-customer-feedback
Previews:
- https://deploy-preview-519--replicated-docs.netlify.app/vendor/snapshots-overview#what-data-is-backed-up
- https://deploy-preview-519--replicated-docs.netlify.app/enterprise/snapshots-understanding
=> 31553: Improve Snapshots Info on What Gets Backed Up and Limitations

docs/enterprise/gitops-workflow.md
Story: https://app.shortcut.com/replicated/story/55540/orange-team-document-changes-to-gitops-ux-workflow
Preview: https://deploy-preview-545--replicated-docs.netlify.app/enterprise/gitops-workflow
=> Updates to gitops workflow

docs/enterprise/snapshots-configuring-hostpath.md, docs/enterprise/snapshots-configuring-nfs.md, docs/enterprise/snapshots-creating.md, docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-restoring-partial.md, docs/enterprise/snapshots-scheduling.md, docs/enterprise/snapshots-storage-destinations.md, docs/enterprise/snapshots-understanding.md, docs/enterprise/snapshots-velero-installing-config.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/56037/consolidate-snapshots-limitations-prerequisites-etc-to-be-more-findable
Previews:
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-understanding
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-velero-installing-config
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-configuring-nfs
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-configuring-hostpath
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-creating
- https://deploy-preview-552--replicated-docs.netlify.app/enterprise/snapshots-schedul …
=> 56037: Improve the Snapshots Content Organization and Add a Workflow

docs/enterprise/snapshots-velero-installing-config.md
This PR is mainly to hopefully fix the way our web site is displaying in an erroneous state. But also, this is a typo that I missed earlier.
Preview: https://deploy-preview-567--replicated-docs.netlify.app/enterprise/snapshots-velero-installing-config#next-step
=> FixItDearHenry: Updated name of cross-reference

docs/reference/template-functions-kurl-context.md, docs/vendor/helm-installing-native-helm.md, docs/vendor/identity-service-configuring.md
SC: https://app.shortcut.com/replicated/story/56379/review-incorrect-usage-of-crd-when-we-mean-cr-in-documentation
Previews: 
- https://deploy-preview-600--replicated-docs.netlify.app/reference/template-functions-kurl-context#kurlall
- https://deploy-preview-600--replicated-docs.netlify.app/vendor/helm-installing-native-helm#native-helm-limitations
- https://deploy-preview-600--replicated-docs.netlify.app/vendor/helm-installing-native-helm#enabling-and-using-native-helm-charts
- https://deploy-preview-600--replicated-docs.netlify.app/vendor/identity-service-configuring
=> 56379: Correct References of CRD to Custom Resource

docs/vendor/packaging-embedded-kubernetes.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/57473/add-host-preflight-info-to-create-a-kubernetes-installer-reorder-nav
Preview: https://deploy-preview-603--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes#customize-host-preflight-checks
=> Add better host preflight info to Creating a Kubernetes Installer

docs/vendor/packaging-embedded-kubernetes.md
SC: https://app.shortcut.com/replicated/story/57473/add-host-preflight-info-to-create-a-kubernetes-installer-reorder-nav
Preview: https://deploy-preview-604--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes#customize-host-preflight-checks-in-either-installer-type
=> 57473-updated: Clarified and Moved Host Preflight Info for Create Kubernetes Installer

docs/vendor/packaging-embedded-kubernetes.md
SC: https://app.shortcut.com/replicated/story/57549/fix-typo-in-link
Preview: https://deploy-preview-607--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes#customize-host-preflight-checks
=> 57549: Fixed typo

docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/58056/edit-kurl-sh-release-notes
Preview: https://deploy-preview-620--replicated-docs.netlify.app/release-notes/rn-kubernetes-installer
=> 58056: Added "Version" and "Release"

docs/vendor/preflight-support-bundle-creating.md, docs/vendor/support-submit-request.md
SC: https://app.shortcut.com/replicated/story/58299/sev-1-issues-are-fixed-3x-faster-with-support-bundles
Previews:
- https://deploy-preview-629--replicated-docs.netlify.app/vendor/support-submit-request
- https://deploy-preview-629--replicated-docs.netlify.app/vendor/preflight-support-bundle-creating
=> 58299: Speedy issue resolution with support bundles

docs/vendor/vendor-portal-creating-account.md
SC: https://app.shortcut.com/replicated/story/58725/style-edit-for-merged-pr-633
Preview: https://deploy-preview-637--replicated-docs.netlify.app/vendor/vendor-portal-creating-account
=> 58725: Style Edits

docs/enterprise/snapshots-creating.md
https://github.com/replicatedhq/replicated-docs/issues/635
=> fix broken link

netlify.toml
https://app.shortcut.com/replicated/story/58815/set-up-netlify-redirects-file
=> Adds netlify.toml with redirects

docs/enterprise/snapshots-velero-cli-installing.md
SC: https://replicated.slack.com/archives/C02BPJQQP28/p1663597053948819
Preview: https://deploy-preview-642--replicated-docs.netlify.app/enterprise/snapshots-velero-cli-installing#install-the-velero-cli-in-an-online-cluster
=> 59054: Clarify Kubernetes installer and existing cluster for Velero CLI

docs/templates/app-configuration.md, docs/templates/troubleshooting.md
@jonquil2002, in preparation for my Replicon presentation, I created a couple more templates that vendors could use:
* Troubleshooting template (useful for vendors, though also really for anyone at Replicated writing docs)
* App configuration template (as in, a topic that would walk an enterprise user through completing the configuration screen)
Story: https://app.shortcut.com/replicated/story/59314/create-app-config-and-troubleshooting-templates-for-vendors
=> Templates for vendors

docs/templates/app-configuration.md, docs/templates/installation-requirements.md
https://app.shortcut.com/replicated/story/59417/install-doc-template
=> Add installation topic template and edit config template

docs/vendor/admin-console-customize-app-icon.md
We no longer show app icons in the the circle so not all of these recommendations are relevant anymore. I'm not sure if just want to remove them or keep some of the recs and and update all of the screenshots
=> Updates to admin console icon recommendations

docs/vendor/preflight-support-bundle-creating.md
SC: https://app.shortcut.com/replicated/story/44681/create-a-vendor-tutorial-doc-for-adding-a-strict-analyzer-to-app-preflights
Previews:
- https://deploy-preview-656--replicated-docs.netlify.app/vendor/preflight-support-bundle-creating#about-preflight-checks-and-support-bundles
- https://deploy-preview-656--replicated-docs.netlify.app/vendor/preflight-support-bundle-creating#define-preflight-checks
=> 44681: Update Strict Preflight Info

.github/workflows/kubernetes-installer-release-notes.yml
https://github.com/replicatedhq/kURL/pull/3521
=> New label to identify kurl automated pr as type feature in release notes

docs/enterprise/installing-general-requirements.md
SC: https://app.shortcut.com/replicated/story/58875/include-operating-system-requirements-for-kurl-in-documentation
Preview:
https://deploy-preview-671--replicated-docs.netlify.app/enterprise/installing-general-requirements#embedded-cluster-requirements
=> 58875: Updated Kubernetes Installer System Requirements

docs/vendor/support-host-support-bundles.md
SC: https://app.shortcut.com/replicated/story/59865/change-title-for-configuring-host-support-bundle-manifest-files
Preview: https://deploy-preview-677--replicated-docs.netlify.app/vendor/support-host-support-bundles
=> 59865: Change Title to Configuring Host Support Bundles Topic

docs/vendor/team-management-rbac-configuring.md, docs/vendor/team-management.md
SC: https://app.shortcut.com/replicated/story/58934/procedure-for-assigning-a-vendor-portal-rbac-policy-to-a-team-member
Previews:
- https://deploy-preview-672--replicated-docs.netlify.app/vendor/team-management#invite-members
- https://deploy-preview-672--replicated-docs.netlify.app/vendor/team-management-rbac-configuring
=> 58934: Assigning RBAC Policies

docs/enterprise/status-viewing-details.md
SC: https://app.shortcut.com/replicated/story/59826/better-document-what-missing-status-means
Previews: https://deploy-preview-694--replicated-docs.netlify.app/enterprise/status-viewing-details#resource-statuses
=> 59826: Explain Missing State Better

docs/enterprise/updating-patching-with-kustomize.md
SC: https://app.shortcut.com/replicated/story/59467/improvements-to-the-patching-with-kustomize-topic
Preview: https://deploy-preview-680--replicated-docs.netlify.app/enterprise/updating-patching-with-kustomize
=> 59467-JQ: Update updating-patching-with-kustomize.md

docs/enterprise/troubleshooting-an-app.md, docs/vendor/support-submit-request.md
SC: https://app.shortcut.com/replicated/story/58743/update-support-request-documentation-to-emphasize-providing-a-support-bundle
Preview: https://deploy-preview-685--replicated-docs.netlify.app/enterprise/troubleshooting-an-app
=> 58743-New: Updated Support Bundle CLI Procedures

docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/60516/pr-to-edit-merged-kurl-rns
The RNs were merged and these are just some minor edits for style.
=> 60516: Minor edits to kURL Release Notes

sidebars.js
https://app.shortcut.com/replicated/story/61032/fix-error-in-toc
=> Fixes error in sidebar

docs/release-notes/rn-kubernetes-installer.md
Updates the link to the EKCO add-on topic to point to the MinIO section specifically
=> Updates xref to EOCK add-on topic

docs/vendor/tutorial-ui-create-app.md, docs/vendor/tutorial-ui-create-customer-license.md, docs/vendor/tutorial-ui-create-customer.md, docs/vendor/tutorial-ui-create-new-version.md, docs/vendor/tutorial-ui-create-release.md, docs/vendor/tutorial-ui-deploy-app.md, docs/vendor/tutorial-ui-install-app-manager.md, docs/vendor/tutorial-ui-update-app.md, netlify.toml, sidebars.js
SC: https://app.shortcut.com/replicated/story/61053/break-out-ui-getting-started-tutorial-into-steps
Preview steps start here: https://deploy-preview-720--replicated-docs.netlify.app/vendor/tutorial-ui-create-app
=> 61053: Break out Getting Started UI tutorial

docs/vendor/tutorial-cli-create-app.mdx, docs/vendor/tutorial-cli-create-customer.mdx, docs/vendor/tutorial-cli-create-new-version.mdx, docs/vendor/tutorial-cli-create-release.mdx, docs/vendor/tutorial-cli-deploy-app.mdx, docs/vendor/tutorial-cli-install-app-manager.mdx, docs/vendor/tutorial-cli-install-cli.mdx, docs/vendor/tutorial-cli-manifests.mdx, docs/vendor/tutorial-cli-new-version.mdx, docs/vendor/tutorial-cli-update-app.mdx, netlify.toml, sidebars.js
https://app.shortcut.com/replicated/story/61054/break-out-cli-getting-started-tutorial-into-steps
Preview: https://deploy-preview-722--replicated-docs.netlify.app/vendor/tutorial-cli-install-cli
=> 61054: Create a CLI Tutorial Section

docs/intro.md
https://github.com/replicatedhq/replicated-docs/issues/748
=> Remove broken link

docs/enterprise/installing-general-requirements.md
https://app.shortcut.com/replicated/story/61207/add-storage-requirements
https://deploy-preview-775--replicated-docs.netlify.app/enterprise/installing-general-requirements#embedded-cluster-requirements
=> Update requirements for rook add-on

docs/partials/linter-rules/_linter-definition.mdx, docs/reference/custom-resource-about.md, docs/reference/custom-resource-lintconfig.md, docs/reference/custom-resource-lintconfig.mdx, docs/reference/linter.mdx, sidebars.js
SC: https://app.shortcut.com/replicated/story/62306/create-a-reference-topic-for-the-lintconfig-custom-resource
Previews:
- https://deploy-preview-783--replicated-docs.netlify.app/reference/custom-resource-about
- https://deploy-preview-783--replicated-docs.netlify.app/reference/custom-resource-lintconfig
- https://deploy-preview-783--replicated-docs.netlify.app/reference/linter
=> 62306: Create LinterConfig CR Topic

docs/vendor/releases-promoting.md
you can create channels from the cli or ui
=> remove cli reference

docs/enterprise/gitops-workflow.md
SC: https://app.shortcut.com/replicated/story/62729/add-gitops-helm-limitation-to-gitops-topic
Preview: https://deploy-preview-798--replicated-docs.netlify.app/enterprise/gitops-workflow#limitations
=> 62729: Add Native Helm Limitation to GitOps

docs/reference/custom-resource-about.md
https://app.shortcut.com/replicated/story/62409/conflicting-info-in-cr-table
Preview: https://deploy-preview-799--replicated-docs.netlify.app/reference/custom-resource-about
=> 62409: Removed Items that are not CRs from Table

docs/vendor/releases-about.md
SC: https://app.shortcut.com/replicated/story/63512/correct-heading
This section is about release promotion and its various considerations (which does include release channel considerations).
Preview: https://deploy-preview-818--replicated-docs.netlify.app/vendor/releases-about#release-promotion
=> 63512: Corrected Heading

docs/vendor/tutorial-cli-setup.mdx, docs/vendor/tutorial-ui-setup.mdx
From https://github.com/replicatedhq/replicated-docs/issues/825
UI: https://deploy-preview-838--replicated-docs.netlify.app/vendor/tutorial-ui-setup
CLI: https://deploy-preview-838--replicated-docs.netlify.app/vendor/tutorial-cli-setup
=> Adds links to existing cluster requirements

docs/enterprise/installing-embedded-cluster.md, docs/enterprise/updating-apps.md, docs/enterprise/updating-embedded-cluster.md, docs/enterprise/updating-existing-cluster.md
SC: https://app.shortcut.com/replicated/story/63912/fix-bug-change-command-to-use-app-slug
Previews:
- https://deploy-preview-839--replicated-docs.netlify.app/enterprise/updating-embedded-cluster
- https://deploy-preview-839--replicated-docs.netlify.app/enterprise/updating-existing-cluster
=> 63912: Bug Fix: Genericize commands for Updating on a Kubernetes Installer Cluster

docs/vendor/support-modular-support-bundle-specs.md
https://github.com/replicatedhq/troubleshoot/pull/918
=> fix label for upstream change troubleshoot/918

docs/enterprise/installing-stateful-component-requirements.md, docs/vendor/packaging-embedded-kubernetes.md, docs/vendor/packaging-installer-storage.md, sidebars.js
Story: https://app.shortcut.com/replicated/story/61326/add-docs-that-explain-how-to-select-storage-options-for-kurl-clusters
Preview for new topic: https://deploy-preview-813--replicated-docs.netlify.app/vendor/packaging-installer-storage
Added new xrefs to this topic in the Creating Installers topic as well: https://deploy-preview-813--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes#include-a-kubernetes-installer-in-an-application-release-beta (see step 2)
=> Adds new topic with guidance for choosing storage add-ons for Installer

docs/reference/linter.mdx
Stories:
- https://app.shortcut.com/replicated/story/63845/missing-linter-documentation-for-nonexsistent-status-informer-object
- https://app.shortcut.com/replicated/story/63838/linter-rules-should-be-sorted-by-something
Preview: https://deploy-preview-855--replicated-docs.netlify.app/reference/linter#nonexsistent-status-informer-object
=> Adds nonexistent status informer rule and alphabetizes

docs/vendor/policies-data-transmission.md
Add bullets for the specific data which is transmitted.
Added language also used for telemetry and reporting.
Added link to the other security info on website.
=> update data transmission policy statements

docs/vendor/support-host-support-bundles.md
SC: https://app.shortcut.com/replicated/story/65438/fix-broken-link-for-host-support-bundles
Preview: https://deploy-preview-863--replicated-docs.netlify.app/vendor/support-host-support-bundles#about-host-support-bundles
=> 65438: Fixed link to Generate a Host Support Bundle

docs/vendor/distributing-workflow.md
SC: https://app.shortcut.com/replicated/stories/space/37255/documentation-team-view
=> 65558: Update distributing-workflow.md

docs/enterprise/installing-general-requirements.md
SC: https://app.shortcut.com/replicated/story/66535/update-k8s-version-compatibility-table
Preview: https://deploy-preview-885--replicated-docs.netlify.app/enterprise/installing-general-requirements#kubernetes-version-compatibility
=> 66535: Updated Kubernetes Version Compatibility Table

docs/enterprise/installing-general-requirements.md, docs/vendor/policies-support-lifecycle.md
Replacing this PR: https://github.com/replicatedhq/replicated-docs/pull/699
https://deploy-preview-887--replicated-docs.netlify.app/vendor/policies-support-lifecycle#supported-versions
https://deploy-preview-887--replicated-docs.netlify.app/enterprise/installing-general-requirements#kubernetes-version-compatibility
=> Add supported versions table

docs/release-notes/rn-kubernetes-installer.md
IMPORTANT: Add note to recommend those that has ubuntu distro do not use this release
=> IMPORTANT: Add note to recommend those that has ubuntu distro do not use this release

docs/reference/kots-validating-sbom.md, sidebars.js
Added a reference document on how to validate the SBOM signatures of a KOTS release.
=> adding SBOM validation directions

docs/partials/custom-resource-application/_proxyRegistryDomain.mdx, docs/partials/custom-resource-application/_replicatedRegistryDomain.mdx, docs/reference/custom-resource-application.md
SC: https://app.shortcut.com/replicated/story/63070/updates-to-custom-registry-domain-feature-for-ga
Preview: https://deploy-preview-908--replicated-docs.netlify.app/reference/custom-resource-application#proxyregistrydomain
=> Add new fields for custom registry domains

docs/enterprise/installing-general-requirements.md
See the new "Port forwarding" bullet point: https://deploy-preview-918--replicated-docs.netlify.app/enterprise/installing-general-requirements#existing-cluster-requirements
Story: https://app.shortcut.com/replicated/story/67732/add-socat-to-the-required-package-list
=> Add socat requirement

docs/enterprise/installing-embedded-cluster.md
Preview: https://deploy-preview-926--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#air-gap
Story: https://app.shortcut.com/replicated/story/68267/fix-formatting-error-in-installation-topic
=> Fix formatting error

docs/vendor/packaging-embedded-kubernetes.md
SC: https://app.shortcut.com/replicated/story/63015/add-information-about-editing-an-installer-after-it-s-been-promoted
Preview: https://deploy-preview-933--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes
=> 63015: Add info about editing installers

docs/enterprise/snapshots-configuring-hostpath.md, docs/enterprise/snapshots-configuring-nfs.md
SC: https://app.shortcut.com/replicated/story/68983/add-example-command-to-velero-prereqs
Previews:
- https://deploy-preview-943--replicated-docs.netlify.app/enterprise/snapshots-configuring-hostpath#prerequisites
=> 68983: Added example to prereqs

docs/intro-replicated.md
https://app.shortcut.com/replicated/story/68859/update-the-description-of-replicated-in-the-intro-topic-to-clarify-embedded-option
https://deploy-preview-945--replicated-docs.netlify.app/intro-replicated
=> Update replicated description

docs/partials/kots-cli/_ensure-rbac.mdx, docs/partials/kots-cli/_help.mdx, docs/partials/kots-cli/_kotsadm-namespace.mdx, docs/partials/kots-cli/_kotsadm-registry.mdx, docs/partials/kots-cli/_namespace.mdx, docs/partials/kots-cli/_registry-password.mdx, docs/partials/kots-cli/_registry-username.mdx, docs/partials/kots-cli/_skip-rbac-check.mdx, docs/partials/kots-cli/_strict-security-context.mdx, docs/partials/kots-cli/_use-minimal-rbac.mdx, docs/partials/kots-cli/_wait-duration.mdx, docs/partials/kots-cli/_with-minio.mdx, docs/reference/kots-cli-admin-console-upgrade.md
https://app.shortcut.com/replicated/story/69060/kots-cli-docs-missing-flags
https://deploy-preview-948--replicated-docs.netlify.app/reference/kots-cli-admin-console-upgrade
=> Add missing admin-console upgrade flags

docs/enterprise/snapshots-velero-cli-installing.md
https://app.shortcut.com/replicated/story/69402/need-to-clarify-an-example-verlero-cli-install-steps
https://deploy-preview-957--replicated-docs.netlify.app/enterprise/snapshots-velero-cli-installing
=> Clarify example command

docs/vendor/packaging-installer-storage.md
https://app.shortcut.com/replicated/story/67354/update-storage-add-ons-topic-with-link-to-migrating-off-longhorn
Preview: https://deploy-preview-964--replicated-docs.netlify.app/vendor/packaging-installer-storage
=> Add xrefs to kURL topic on migrating CSI add-on

docs/vendor/custom-domains.md
SC: https://app.shortcut.com/replicated/story/67611/feature-custom-domain-download-portal
Preview: https://deploy-preview-907--replicated-docs.netlify.app/vendor/custom-domains#about-custom-domains
=> HOLD FOR RELEASE - 67611: Custom Domains for Download Portal

docs/reference/replicated-cli-installing.md
https://replicated.slack.com/archives/C036BTS7JCE/p1676916020833119?thread_ts=1676915228.664939&cid=C036BTS7JCE
https://github.com/replicatedhq/replicated-docs/issues/970
=> Update the curl command for Mac installations

docs/release-notes/rn-kubernetes-installer.md
This release was rolled back and the release notes must be removed.
=> Removed v2023.02.17-0 from release notes

docs/vendor/team-management-rbac-resource-names.md
documents the new custom hostname rbac resource names
=> documents the new custom hostname rbac resource names

docs/enterprise/snapshots-config-workflow.md, docs/enterprise/snapshots-configuring-hostpath.md, docs/enterprise/snapshots-configuring-nfs.md, docs/enterprise/snapshots-creating.md, docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-storage-destinations.md, docs/enterprise/snapshots-understanding.md
SC: https://app.shortcut.com/replicated/story/69220/improve-about-backup-and-restore
Previews:
- https://deploy-preview-983--replicated-docs.netlify.app/enterprise/snapshots-understanding
- https://deploy-preview-983--replicated-docs.netlify.app/enterprise/snapshots-creating
- https://deploy-preview-983--replicated-docs.netlify.app/enterprise/snapshots-restoring-full
- https://deploy-preview-983--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations
=> 69220: Rewrite About Backup and Restore

docs/enterprise/snapshots-configuring-hostpath.md, docs/enterprise/snapshots-configuring-nfs.md, docs/enterprise/snapshots-creating.md, docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-storage-destinations.md, docs/enterprise/snapshots-understanding.md, docs/enterprise/snapshots-velero-cli-installing.md, docs/enterprise/snapshots-velero-installing-config.md, docs/partials/snapshots/_updateDefaultStorage.mdx, netlify.toml, sidebars.js
SC: https://app.shortcut.com/replicated/story/70763/move-content-and-delete-how-to-snapshots-topic
Previews:
- https://deploy-preview-989--replicated-docs.netlify.app/enterprise/snapshots-configuring-hostpath#next-steps
- https://deploy-preview-989--replicated-docs.netlify.app/enterprise/snapshots-configuring-nfs#next-steps
- https://deploy-preview-989--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations#next-steps
- https://deploy-preview-989--replicated-docs.netlify.app/enterprise/snapshots-creating#prerequisite
- https://deploy-preview-989--replicated-docs.netlify.app/enterprise/snapshots-velero-installing-config
- https://deploy-preview-989--replicated-docs.netlify.app/enterprise/snapshots-understanding#restores
- …
=> 70763: Remove "How to Set Up Backup Storage" topic

docs/vendor/licenses-about-types.md
SC: https://app.shortcut.com/replicated/story/69153/add-details-to-customer-license-types
Preview: https://deploy-preview-990--replicated-docs.netlify.app/vendor/licenses-about-types#updating-a-customer-license-type
=> 69153: Added license update info

docs/enterprise/snapshots-configuring-hostpath.md, docs/enterprise/snapshots-configuring-nfs.md, docs/enterprise/snapshots-storage-destinations.md, docs/partials/snapshots/_checkVersion.mdx, docs/partials/snapshots/_installVelero.mdx, docs/partials/snapshots/_registryCredentialsNote.mdx
SC: https://app.shortcut.com/replicated/story/70342/update-note-about-registry-credentials-for-air-gap-velero-install
Previews: 
- https://deploy-preview-992--replicated-docs.netlify.app/enterprise/snapshots-configuring-hostpath#install-velero-and-configure-host-path-storage-in-air-gapped-environments
- https://deploy-preview-992--replicated-docs.netlify.app/enterprise/snapshots-configuring-nfs#install-velero-and-configure-nfs-storage-in-air-gapped-environments
- https://deploy-preview-992--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations#configure-s3-compatible-storage-for-air-gapped-environments
=> 70342: Clarified registry credentials note for air gap

docs/release-notes/rn-app-manager.md
SC: https://app.shortcut.com/replicated/story/71533/correction-to-rn-xref-link
=> 71533: Add topic name to Xref in RN

docs/enterprise/updating-embedded-cluster.md
added info here: https://deploy-preview-980--replicated-docs.netlify.app/enterprise/updating-embedded-cluster#add-ons
See related kurl PR: https://github.com/replicatedhq/kurl.sh/pull/945#discussion_r1116007011
=> Remove incorrect info about docker and containerd

docs/enterprise/snapshots-understanding.md, docs/enterprise/snapshots-updating-with-admin-console.md, docs/enterprise/snapshots-velero-cli-installing.md, docs/enterprise/snapshots-velero-installing-config.md
SC: https://app.shortcut.com/replicated/story/57050/improve-velero-air-gapped-installation-config
Previews:
- https://deploy-preview-994--replicated-docs.netlify.app/enterprise/snapshots-velero-cli-installing
- https://deploy-preview-994--replicated-docs.netlify.app/enterprise/snapshots-velero-installing-config
- https://deploy-preview-994--replicated-docs.netlify.app/enterprise/snapshots-updating-with-admin-console#update-storage-settings
=> 57050: Snapshots clarifications for air gap

docs/release-notes/rn-kubernetes-installer.md
Add missing change - kurl release
=> Add missing change - kurl release

docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-understanding.md, docs/partials/snapshots/_restoreTable.mdx, docs/vendor/snapshots-hooks.md, docs/vendor/snapshots-overview.md
SC: https://app.shortcut.com/replicated/story/70729/create-test-pr-for-vendor-enterprise-bridge-topic
This PR replaces the previous test PR because I wanted to pick up all of the other changes to Backup/Restore that were in flight.
Preview: 
- https://deploy-preview-1003--replicated-docs.netlify.app/vendor/snapshots-overview
- - https://deploy-preview-1003--replicated-docs.netlify.app/vendor/snapshots-hooks#about-backup-and-restore-hooks
=> 70729-NEW: Updated Vendor bridge topic for Backup/Restore

docs/enterprise/snapshots-creating.md
SC: https://app.shortcut.com/replicated/story/31118/docs-snapshots-troubleshooting-docs-should-help-a-multi-app-user-recover-in-a-dr-scenario-where-not-all-apps-were-included
Preview: https://deploy-preview-1009--replicated-docs.netlify.app/enterprise/snapshots-creating#prerequisites
=> 31118: Add Prereq for Multi Apps to Enterprise Backups

docs/vendor/tutorial-ui-update-app.md
SC: https://app.shortcut.com/replicated/story/72062/404-on-https-docs-replicated-com-vendor-tutorial-ui-update-app-yaml-in-a-git-repository-see-the-cli-quickstart-tutorial
=> 72062: Fixed link in Update App Tutorial

docs/reference/custom-resource-backup.md, docs/vendor/snapshots-configuring-backups.md
SC: https://app.shortcut.com/replicated/story/71999/improve-backups-vendor-content
Minor changes here: https://deploy-preview-1012--replicated-docs.netlify.app/vendor/snapshots-configuring-backups
Lotsa changes here: https://deploy-preview-1012--replicated-docs.netlify.app/reference/custom-resource-backup
=> 71999: Improve Backup CR Info

docs/partials/status-informers/_aggregateStatus.mdx, docs/partials/status-informers/_statusesTable.mdx
Fixing MDX syntax for tables. Need a <tbody> tags and colspan should be colSpan.
=> fix mdx syntax tables

docusaurus.config.js
checkpoint before docusaurus  2.4.1. upgrade
=> This is the last commit using docusaurus  2.0.0-beta.9

sidebars.js
SC: https://app.shortcut.com/replicated/story/73844/move-patching-with-kustomize-in-toc
=> 73844: Move Patching w/Kustomize in TOC

docs/enterprise/image-registry-settings.md, docs/partials/image-registry/_image-registry-settings.mdx
SC: https://app.shortcut.com/replicated/story/73080/document-how-to-change-private-registry-settings-for-air-gap-after-installation
Previews:
-https://deploy-preview-1055--replicated-docs.netlify.app/enterprise/image-registry-settings#configure-private-registries-for-online-clusters
- https://deploy-preview-1055--replicated-docs.netlify.app/enterprise/image-registry-settings#air-gap
=> 73080: Add a Change Private Registry for Air Gap Procedure

sidebars.js
SC: https://app.shortcut.com/replicated/story/73937/move-helm-deployment-in-toc
Preview: https://deploy-preview-1057--replicated-docs.netlify.app/
=> 73937: Move Helm Chart Deployment in TOC

docs/partials/helm/_replicated-deprecated.mdx
See the partial rendered on this topic: https://deploy-preview-1059--replicated-docs-upgrade.netlify.app/vendor/helm-overview#replicated-helm
=> Remove deprecated language

docs/vendor/helm-overview.md
Steps 1-5 in the Native Helm process: https://deploy-preview-1060--replicated-docs.netlify.app/vendor/helm-overview#native
=> fix numbering sequence

docs/reference/kots-cli-install.md
https://deploy-preview-1065--replicated-docs-upgrade.netlify.app/reference/kots-cli-install
=> Fix broken links

docs/vendor/helm-optional-value-keys.md
SC: https://app.shortcut.com/replicated/story/72532/rewrite-helm-topic-optional-value-keys
Preview: https://deploy-preview-1063--replicated-docs-upgrade.netlify.app/vendor/helm-optional-value-keys
=> 72532: Improve Content in Optional Value Keys

docs/partials/helm/_hooks-limitation.mdx, docs/partials/helm/_native-helm-limitations.mdx, docs/vendor/helm-native-helm-install-order.md, docs/vendor/helm-overview.md
https://app.shortcut.com/replicated/story/74562/update-helm-docs-about-supported-not-supported-hooks
Previews:
- Added to limitations: https://deploy-preview-1072--replicated-docs.netlify.app/vendor/helm-overview#replicated-helm-limitations
- Added to Hooks section in Defining Installation order: https://deploy-preview-1072--replicated-docs.netlify.app/vendor/helm-native-helm-install-order#hooks
=> Add hook limitations to partial

docs/enterprise/installing-general-requirements.mdx
See https://github.com/replicatedhq/replicated-docs/issues/1084
https://deploy-preview-1085--replicated-docs-upgrade.netlify.app/enterprise/installing-general-requirements#kubernetes-version-compatibility
=> Update k8s compatibility table

docs/vendor/admin-console-customize-config-screen.md, docs/vendor/config-screen-about.md
SC: https://app.shortcut.com/replicated/story/73619/orange-team-regex-config
Previews:
- https://deploy-preview-1049--replicated-docs-upgrade.netlify.app/vendor/config-screen-about
- https://deploy-preview-1049--replicated-docs-upgrade.netlify.app/vendor/admin-console-customize-config-screen#about-regular-expression-validation
- https://deploy-preview-1049--replicated-docs-upgrade.netlify.app/vendor/admin-console-customize-config-screen#add-fields-to-the-configuration-screen
=> HOLD FOR RELEASE - 73619: Regex Feature

docs/release-notes/rn-kubernetes-installer.md
=> Add 2 containerd migrations in release notes

docs/vendor/helm-release-creating-package.md, docs/vendor/helm-release.mdx, sidebars.js
SC: https://app.shortcut.com/replicated/story/73614/make-helm-chart-packaging-its-own-topic
=> 73614-NEW: Make Helm Chart Packaging a Standalone Topic

docs/enterprise/updating-tls-cert.md, docs/vendor/custom-domains.md
https://app.shortcut.com/replicated/story/75359/bug-fix-admonitions
=> Fix important admonitions

docusaurus.config.js
remove commented out config lines that are no longer needed
=> clean up. remove commented out config lines that are no longer needed

docs/partials/install/_prereqs-embedded-cluster.mdx
See https://deploy-preview-1115--replicated-docs.netlify.app/enterprise/installing-embedded-cluster
=> Fix typo in embedded prereqs

docs/vendor/helm-install.md, docs/vendor/helm-overview.md
SC: https://app.shortcut.com/replicated/story/75280/update-the-about-deploying-with-helm-topic
Preview: https://deploy-preview-1114--replicated-docs-upgrade.netlify.app/vendor/helm-overview
=> 75280: Improve Helm Deployment Content

docs/enterprise/installing-embedded-airgapped.md, docs/enterprise/installing-embedded-cluster.md, docs/enterprise/installing-existing-cluster-airgapped.md, docs/enterprise/installing-existing-cluster.md, docs/enterprise/installing-general-requirements.mdx, docs/partials/image-registry/_image-registry-airgap-about.mdx, docs/partials/image-registry/_image-registry-airgap-prereq.mdx, docs/partials/install/_airgap-bundle-prereq.mdx, docs/partials/install/_embedded-admin-console-step.mdx, docs/partials/install/_embedded-ha-step.mdx, docs/partials/install/_embedded-login-password.mdx, docs/partials/install/_kots-cli-install.mdx, docs/partials/install/_license-file-prereq.mdx, docs/partials/install/_prereqs-embedded-cluster.mdx, docs/partials/install/_prereqs-existing-cluster.mdx
Most edits are:
- Here https://deploy-preview-1123--replicated-docs.netlify.app/enterprise/installing-embedded-airgapped 
- and here https://deploy-preview-1123--replicated-docs.netlify.app/enterprise/installing-general-requirements#private-registry-requirements
https://app.shortcut.com/replicated/story/75936/correct-air-gap-steps-for-kurl-install
=> Correct air gap install for kurl clusters

.github/workflows/algolia-crawl.yml, .github/workflows/app-manager-release-notes.yml, .github/workflows/kubernetes-installer-release-notes.yml
Updates `actions/checkout` from v2 to v3.
=> update action/checkout to v3

docs/vendor/policies-support-lifecycle.md
https://app.shortcut.com/replicated/story/77158/update-support-policies-with-k8s-1-27
Preview: https://deploy-preview-1147--replicated-docs.netlify.app/vendor/policies-support-lifecycle#supported-versions
=> Updates support policies with k8s 1.27

docs/partials/helm/_helm-cli-limitations.mdx, docs/vendor/helm-install.md
https://app.shortcut.com/replicated/story/77123/remove-helm-cli-beta-documentation-about-admin-console-helm-chart
=> HOLD FOR RELEASE: Remove mention of admin-console Helm chart (Part I)

docs/vendor/policies-data-transmission.md
Add link to the About Instance and Event Data and update the Last Modified text
=> Add link to the About Instance and Event Data

docs/reference/kots-cli-remove.md
https://app.shortcut.com/replicated/story/73917/explain-how-the-undeploy-flag-determines-what-to-delete
Preview: https://deploy-preview-1166--replicated-docs.netlify.app/reference/kots-cli-remove
=> Sc73917: Explain --undeploy flag

docs/partials/install/_kubernetes-compatibility.mdx, docs/vendor/policies-support-lifecycle.md
https://deploy-preview-1183--replicated-docs.netlify.app/release-notes/rn-app-manager#kubernetes-compatibility
https://deploy-preview-1183--replicated-docs.netlify.app/vendor/policies-support-lifecycle#supported-versions
=> Adds 1.27 support

docs/vendor/orchestrating-resource-deployment.md, sidebars.js
[SC-77370](https://app.shortcut.com/replicated/story/77370/implement-kots-wait-for-ready-feature-for-native-kubernetes-manifests)
Supporting documentation for https://github.com/replicatedhq/kots/pull/3903
=> add section for orchestrating resource deployment

docs/release-notes/rn-app-manager.md, docs/vendor/orchestrating-resource-deployment.md
SC: https://app.shortcut.com/replicated/story/78308/edit-notes-in-new-orchestration-topic
Preview: https://deploy-preview-1185--replicated-docs-upgrade.netlify.app/vendor/orchestrating-resource-deployment
=> 78308: Changed the wording in the notes for Orchestration

docs/enterprise/delete-admin-console.md, docs/enterprise/snapshots-configuring-hostpath.md, docs/enterprise/snapshots-configuring-nfs.md, docs/enterprise/snapshots-creating.md, docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-storage-destinations.md, docs/enterprise/snapshots-troubleshooting-backup-restore.md, docs/enterprise/snapshots-understanding.md, docs/enterprise/snapshots-updating-with-admin-console.md, docs/enterprise/snapshots-velero-cli-installing.md, docs/enterprise/snapshots-velero-installing-config.md, docs/enterprise/status-viewing-details.md, docs/partials/snapshots/_registryCredentialsNote.mdx, docs/partials/snapshots/_restoreTable.mdx, docs/partials/snapshots/_updateDefaultStorage.mdx
SC: https://app.shortcut.com/replicated/story/78338/rebranding-kots-backup-restore-troubleshooting
Previews:
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-understanding
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-velero-cli-installing
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-configuring-hostpath
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-configuring-nfs
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-velero-installing-config
- https://deploy-preview-1187--replicated-docs.netlify.app/enterprise/snapshots-creating
- …
=> DO NOT MERGE 78338: Rebrand Enterprise Snapshots and Troubleshooting

docs/vendor/admin-console-adding-buttons-links.md
https://app.shortcut.com/replicated/story/78487/missing-rebrand-topics-1
=> missing app managers

docs/vendor/packaging-private-images.md
https://deploy-preview-1209--replicated-docs.netlify.app/vendor/packaging-private-images#configure-access-to-an-external-registry
https://app.shortcut.com/replicated/story/79489/add-docs-about-setting-up-gcp-as-private-registry
=> Fix private registries content

docs/vendor/helm-release.md
https://replicated.slack.com/archives/C02BPJQQP28/p1686251373240309
https://deploy-preview-1211--replicated-docs.netlify.app/vendor/helm-release#about-the-helmchart-custom-resource
=> add xref to helmchart CR topic

docs/vendor/preflight-helm-defining.mdx, docs/vendor/preflight-kots-defining.mdx, docs/vendor/support-bundle-helm-customizing.mdx
Previews:
- https://deploy-preview-1240--replicated-docs.netlify.app/vendor/preflight-helm-defining
- https://deploy-preview-1240--replicated-docs.netlify.app/vendor/support-bundle-helm-customizing
https://app.shortcut.com/replicated/story/80758/nest-create-custom-resource-and-create-secret-under-input-kind
Related to https://github.com/replicatedhq/replicated-docs/issues/1228
=> Nest secret and CR sections under input kind

docs/enterprise/installing-embedded-airgapped.md, docs/enterprise/updating-embedded-cluster.md, docs/partials/install/_airgap-bundle-prereq.mdx, docs/partials/install/_intro-embedded.mdx, docs/partials/install/_license-file-prereq.mdx, docs/partials/install/_provision-cluster-intro.mdx, docs/partials/updating/_installerRequirements.mdx
Previews:
- https://deploy-preview-1239--replicated-docs.netlify.app/enterprise/updating-embedded-cluster#air-gap-environments
- https://deploy-preview-1239--replicated-docs.netlify.app/enterprise/installing-embedded-airgapped#install-app
Story: https://app.shortcut.com/replicated/story/80976/updating-embedded-cluster-air-gap-environments-is-not-accurate-for-airgap
=> Correct kurl air gap instructions

docs/vendor/helm-image-registry.md, sidebars.js
https://app.shortcut.com/replicated/story/80533/update-topic-on-using-custom-registries-for-new-helm-install-option
https://deploy-preview-1233--replicated-docs-upgrade.netlify.app/vendor/helm-image-registry
=> Use External private registry for Helm installs

docs/vendor/licenses-about-types.md
https://app.shortcut.com/replicated/story/79966/update-community-licenses-info-in-docs-to-remove-reference-that-it-s-only-for-enterprise-plans
Preview: https://deploy-preview-1241--replicated-docs.netlify.app/vendor/licenses-about-types#community-licenses
=> Edit community licenses content

docs/vendor/releases-about-channels.md, docs/vendor/releases-creating-channels.md
https://app.shortcut.com/replicated/story/80848/update-about-channels-topic-for-builders
https://deploy-preview-1231--replicated-docs.netlify.app/vendor/releases-about-channels
https://deploy-preview-1231--replicated-docs.netlify.app/vendor/releases-creating-channels
=> Edit Channels pages for Builders

docs/vendor/releases-creating-cli.mdx
https://app.shortcut.com/replicated/story/80881/update-managing-releases-with-the-cli-for-helm-only-releases-with-the-chart-flag
https://deploy-preview-1232--replicated-docs.netlify.app/vendor/releases-creating-cli
=> Creating Helm Chart Release with CLI

docs/partials/replicated-cli/_chart-yaml-dir-reqs.mdx, docs/partials/replicated-cli/_yaml-dir.mdx, docs/reference/replicated-cli-release-create.md
Story: https://app.shortcut.com/replicated/story/80746/add-chart-to-the-replicated-cli-docs
Preview: https://deploy-preview-1234--replicated-docs.netlify.app/reference/replicated-cli-release-create
=> add documentation for the --chart flag for the cli

docs/partials/helm/_name-limitation.mdx, docs/vendor/helm-image-registry.mdx
SC: https://app.shortcut.com/replicated/story/82188/add-partial-to-image-pull-secret-for-sdk
Preview: https://deploy-preview-1257--replicated-docs.netlify.app/vendor/helm-image-registry#deliver-image-pull-secrets-for-the-proxy-service
=> 82188: Add limitation to image pull secret

docs/partials/custom-domains/_limitations.mdx
SC: https://app.shortcut.com/replicated/story/81689/missing-custom-domains-limitation
Previews:
- https://deploy-preview-1258--replicated-docs.netlify.app/vendor/custom-domains-download-portal#limitations
- https://deploy-preview-1258--replicated-docs.netlify.app/vendor/custom-domains#limitations
=> 81689: Update _limitations.mdx

docs/partials/instance-insights/_notifications-about.mdx
=> Update _notifications-about.mdx - spelling

docs/partials/replicated-sdk/_beta.mdx, docs/reference/replicated-sdk-apis.md, docs/vendor/helm-image-registry.mdx, docs/vendor/helm-install-release.md, docs/vendor/helm-install.md, docs/vendor/install-with-helm.md, docs/vendor/licenses-reference-helm.md, docs/vendor/licenses-verify-fields-sdk-api.md, docs/vendor/policies-support-lifecycle.md, docs/vendor/replicated-sdk-development.md, docs/vendor/replicated-sdk-overview.md, docs/vendor/replicated-sdk-using.md
SC: https://app.shortcut.com/replicated/story/82256/add-beta-label-to-sdk-docs
=> 82256: Changed SDK Alpha to Beta

docs/vendor/custom-domains.md
SC: https://app.shortcut.com/replicated/story/81713/easily-add-a-custom-domain-for-a-second-app
Preview: https://deploy-preview-1259--replicated-docs.netlify.app/vendor/custom-domains#reuse-a-custom-domain-for-additional-applications
=> 81713: Reuse Custom Domain in Other Apps

docs/vendor/licenses-reference-helm.md, docs/vendor/licenses-verify-fields-sdk-api.md, docs/vendor/releases-creating-customer.md
SC: https://app.shortcut.com/replicated/story/82343/remove-installation-requirement-for-sdk-docs
Previews: 
- https://deploy-preview-1263--replicated-docs-upgrade.netlify.app/vendor/licenses-reference-helm#before-install
- https://deploy-preview-1263--replicated-docs-upgrade.netlify.app/vendor/licenses-reference-helm#runtime
=> 82343: Remove SDK Requirement from Before Installation

docs/reference/replicated-cli-customer-ls.md
Change --appversion flag to be --app-version
modified:   docs/reference/replicated-cli-customer-ls.md
=> Change --appversion flag to be --app-version

docs/vendor/custom-domains-using.md
SC: https://app.shortcut.com/replicated/story/82860/fix-registries-info-in-custom-domains
Preview: https://deploy-preview-1274--replicated-docs.netlify.app/vendor/custom-domains-using#remove-a-custom-domain
=> 82860: Fix Remove Custom Domains Content

docs/vendor/licenses-adding-custom-fields.md
https://app.shortcut.com/replicated/story/83166/license-fields-help-document-not-same-as-in-the-vendor-portal
https://deploy-preview-1287--replicated-docs.netlify.app/vendor/licenses-adding-custom-fields#create-custom-license-fields
=> Hidden field avaiable for KOTS only

docs/vendor/install-with-helm.md, docs/vendor/replicated-sdk-rbac.md, sidebars.js
https://deploy-preview-1299--replicated-docs.netlify.app/vendor/replicated-sdk-rbac
=> Customize RBAC for the SDK

docs/vendor/replicated-sdk-overview.md
SC: https://app.shortcut.com/replicated/story/83276/add-clarity-to-how-to-use-custom-license-fields-in-a-helm-chart
Previews: https://deploy-preview-1311--replicated-docs.netlify.app/vendor/replicated-sdk-overview#replicated-values
=> 83276: Add Custom License Fields to About SDK Helm Values

docs/vendor/customer-adoption.md
SC: https://app.shortcut.com/replicated/story/84043/amber-issue-adoption-report-is-ga
Preview: https://deploy-preview-1313--replicated-docs.netlify.app/vendor/customer-adoption
=> Remove Beta from Adoption Report Topic

sidebars.js
SC: https://app.shortcut.com/replicated/story/84055/amber-issue-quirky-docusaurus-behavior-with-toc
=> Fixed Sidebar re: App Status

docs/vendor/instance-notifications-config.mdx
SC: https://app.shortcut.com/replicated/story/84156/change-notifications-alpha-to-beta
=> 84156: Change Notifications Alpha to Beta

docs/partials/helm/_feature-flag.mdx, docs/vendor/helm-install-release.md, docs/vendor/install-with-helm.md
SC https://app.shortcut.com/replicated/story/84164/amber-issue-install-with-helm-entitlement
=> 84164: Remove Helm Feature Flag

docs/reference/custom-resource-about.md
https://deploy-preview-1324--replicated-docs.netlify.app/reference/custom-resource-about
=> Add v2 helmchart to overview table

docs/partials/helm/_helm-cr-weight.mdx, docs/reference/custom-resource-helmchart-v2.mdx, docs/reference/custom-resource-helmchart.mdx
see https://github.com/replicatedhq/replicated-docs/pull/1117
https://deploy-preview-1326--replicated-docs-upgrade.netlify.app/reference/custom-resource-helmchart-v2#weight
https://deploy-preview-1326--replicated-docs-upgrade.netlify.app/reference/custom-resource-helmchart#weight
=> Add undeploy info to weight field

docs/vendor/distributing-workflow.md, docs/vendor/preflight-helm-defining.mdx, docs/vendor/replicated-onboarding.md
https://app.shortcut.com/replicated/story/84394/change-helm-cli-to-helm-cli
Just found a few instances
=> Helm CLI capitalization

docs/partials/replicated-sdk/_dependency-yaml.mdx, docs/vendor/helm-install-release.md, docs/vendor/replicated-onboarding.md, docs/vendor/replicated-sdk-overview.md
SC: https://app.shortcut.com/replicated/story/84057/update-the-sdk-dependency-yaml-block-to-be-a-partial
=> 84057: Create a Partial for SDK Dependencies

docs/vendor/replicated-sdk-overview.md
https://github.com/replicatedhq/replicated-docs/issues/1342
https://deploy-preview-1343--replicated-docs-upgrade.netlify.app/vendor/replicated-sdk-overview#replicated-values
=> Clarify when values are injected during install

docs/reference/custom-resource-config.md
SC: https://app.shortcut.com/replicated/story/84713/change-br-to-p-in-cr-topic
=> 84713: Changed <br> to <p>

docs/reference/replicated-cli-cluster-create.md, docs/reference/replicated-cli-cluster-kubeconfig.md, docs/reference/replicated-cli-cluster-ls.md, docs/reference/replicated-cli-cluster-rm.md, docs/vendor/testing-about.md, docs/vendor/testing-how-to.md, docs/vendor/testing-replicated-instance-types.md, docs/vendor/testing-supported-clusters.md, sidebars.js
SC: https://app.shortcut.com/replicated/story/84786/add-beta-label-to-c11y-matrix-docs
=> 84786: Add Beta label to Compatibility Matrix

docs/vendor/helm-install-release.md
Preview https://deploy-preview-1366--replicated-docs.netlify.app/vendor/helm-install-release
=> Edit Helm package first step

docs/reference/replicated-cli-cluster-prepare.md, docs/reference/replicated-cli-cluster-rm.md, docs/vendor/testing-how-to.md, sidebars.js
https://app.shortcut.com/replicated/story/84992/document-cluster-prepare-command-for-helm-charts
Preview: https://deploy-preview-1376--replicated-docs.netlify.app/reference/replicated-cli-cluster-prepare
=> feat: document cluster prepare cmd

docs/vendor/licenses-verify-fields-sdk-api.md
https://app.shortcut.com/replicated/story/86764/review-signature-verification-pr
https://deploy-preview-1385--replicated-docs.netlify.app/vendor/licenses-verify-fields-sdk-api
=> Edits to the license field signature verification topic

docs/vendor/team-management-github-username.mdx
https://deploy-preview-1388--replicated-docs-upgrade.netlify.app/vendor/team-management-github-username
=> Reorg collab repo topic

docs/intro.md
https://replicated.slack.com/archives/C02BPJQQP28/p1692879290679309
https://app.shortcut.com/replicated/story/87545/update-kots-and-kurl-installers-tiles-on-landing-page
=> update kots and kurl description

docs/release-notes/rn-whats-new.md
https://github.com/replicatedhq/replicated-docs/issues/1394
=> add links to the component release notes topics

docs/vendor/helm-image-registry.mdx, docs/vendor/private-images-about.md
https://deploy-preview-1410--replicated-docs.netlify.app/vendor/helm-image-registry
=> Remove beta label from proxying images for helm installs

docs/reference/replicated-sdk-apis.md
Link to custom metrics docs in https://github.com/replicatedhq/replicated-docs/pull/1408
=> Link to custom metrics api

docs/release-notes/rn-kubernetes-installer.md
this bug was solved but not automatically added to the release notes.
=> chore: add missing fixed bug to release notes

docs/reference/replicated-cli-cluster-kubeconfig.md, docs/reference/replicated-cli-cluster-upgrade.md, docs/vendor/testing-how-to.md, sidebars.js
=> feat (cmx): replicated cluster upgrade command

docs/vendor/custom-metrics.md
#1469
https://deploy-preview-1471--replicated-docs.netlify.app/vendor/custom-metrics#overview
=> Add more why to custom metrics

docs/vendor/install-with-helm.md
https://deploy-preview-1496--replicated-docs.netlify.app/vendor/install-with-helm
=> Add note about advanced helm install instructions

docs/vendor/install-with-helm.md, docs/vendor/replicated-sdk-customizing.md, netlify.toml, sidebars.js
This PR adds supporting documentation for the feature added in https://github.com/replicatedhq/replicated-sdk/pull/96.
=> [HOLD FOR SDK RELEASE] add section for customizing environment variables

docs/vendor/team-management-rbac-resource-names.md
=> fix rbac heading size

docs/vendor/replicated-sdk-customizing.md
Supporting docs for https://github.com/replicatedhq/replicated-sdk/pull/104
=> docs for adding tolerations to sdk

docs/vendor/instance-data-export.md
Incorporate bulk data export endpoint  into export data documentation.
=> Siva/sc 92122/publish docs for data export

docs/reference/template-functions-static-context.md
Small docs update to support https://github.com/replicatedhq/kots/pull/4119
=> [HOLD FOR RELEASE] add OKE for distribution template function

docs/enterprise/installing-general-requirements.md
https://deploy-preview-1622--replicated-docs.netlify.app/enterprise/installing-general-requirements#minimum-system-requirements-1
=> Update UDP port requirements

docs/vendor/private-images-replicated.md
https://github.com/replicatedhq/replicated-docs/issues/1617
=> Add limitation about provenance attestations

docs/enterprise/snapshots-troubleshooting-backup-restore.md, docs/enterprise/snapshots-velero-installing-config.md, docs/partials/snapshots/_node-agent-mem-limit.mdx
https://deploy-preview-1666--replicated-docs.netlify.app/enterprise/snapshots-troubleshooting-backup-restore#memory-limit-reached-on-the-node-agent-pod
https://deploy-preview-1666--replicated-docs.netlify.app/enterprise/snapshots-velero-installing-config#configure-memory-limit
=> Add commands for increasing mem limit for velero

docs/enterprise/image-registry-rate-limits.md, docs/vendor/helm-native-v2-using.md, sidebars.js
https://deploy-preview-1663--replicated-docs.netlify.app/vendor/helm-native-v2-using
https://deploy-preview-1663--replicated-docs.netlify.app/enterprise/image-registry-rate-limits
=> Update docker hub rate limiting intructions

docs/vendor/install-with-helm.md
https://deploy-preview-1702--replicated-docs.netlify.app/vendor/install-with-helm#install
=> Clarify that channel slug is lowercased

docs/vendor/instance-data-export.md
New columns have been added to the instances report https://replicated-vendor-api.readme.io/reference/listappcustomerinstances
Rendered page:
=> Document new columns for CSV export

docs/partials/replicated-cli/_output.mdx, docs/reference/replicated-cli-cluster-create.md, docs/reference/replicated-cli-cluster-update-ttl.md, docs/vendor/testing-about.md, sidebars.js
New topic: https://deploy-preview-1744--replicated-docs.netlify.app/reference/replicated-cli-cluster-update-ttl
=> Add cluster update ttl docs

docs/vendor/policies-vulnerability-patch.md
https://deploy-preview-1770--replicated-docs.netlify.app/vendor/policies-vulnerability-patch
=> Fixes to vulnerability patch policy

docs/vendor/instance-data-export.md
=> Update CSV data dictionary with instance tags

docs/vendor/instance-insights-details.md
Update instance information bullet points
=> Update instance information

docs/vendor/policies-data-transmission.md
Include more information about the resource statuses, instance details and custom metrics.
Bump the last modified date.
=> Include more information about the resource statuses, instance details and custom metrics.

docs/vendor/policies-support-lifecycle.md
Moves Native Installer from LA to EOA status given the official transition date to EOA is Jan 1 2024
=> DO NOT MERGE BEFORE JAN 1 2024 - Update Native Lifecycle status

docs/vendor/kots-faq.md, sidebars.js
Preview: [KOTS Terminology and FAQs](https://deploy-preview-1751--replicated-docs-upgrade.netlify.app/vendor/kots-faq)
=> Add KOTS FAQs

docs/partials/replicated-sdk/_kots-version-req.mdx, docs/vendor/replicated-sdk-installing.md, docs/vendor/tutorial-kots-helm-install-kots.md
https://deploy-preview-1816--replicated-docs.netlify.app/vendor/replicated-sdk-installing
=> Add kots version req for sdk installs

docs/vendor/policies-infrastructure-and-subprocessors.md
https://github.com/replicatedhq/replicated-docs/issues/1775
=> Add last modified date

docs/vendor/custom-domains-using.md, docs/vendor/instance-notifications-config.mdx, docs/vendor/packaging-embedded-kubernetes.md, docs/vendor/packaging-private-images.md, docs/vendor/releases-creating-channels.md, docs/vendor/releases-creating-cli.mdx, docs/vendor/releases-creating-customer.md, docs/vendor/releases-creating-releases.mdx, docs/vendor/releases-sharing-license-install-script.md, docs/vendor/testing-how-to.md, docs/vendor/vendor-portal-manage-app.md
From https://github.com/replicatedhq/replicated-docs/issues/1839
=> Add links to cli and api docs

docs/enterprise/installing-existing-cluster-automation.md
https://github.com/replicatedhq/replicated-docs/issues/1659
=> Add info about preflights for automated install

docs/partials/replicated-sdk/_dependency-yaml.mdx
bumps the SDK version to 1.0.0-beta.14
=> sdk 1.0.0-beta.14

docs/intro-replicated.md
Development lifecycle > distribution life cycle
=> Distribution life cycle language fix

docs/vendor/kots-faq.md
https://deploy-preview-1972--replicated-docs.netlify.app/vendor/kots-faq#can-i-use-my-own-branding-for-kots-installations
=> Clarify KOTS branding FAQ

docs/enterprise/updating-patching-with-kustomize.md, docs/vendor/helm-native-about.mdx
https://deploy-preview-1984--replicated-docs-upgrade.netlify.app/enterprise/updating-patching-with-kustomize
https://deploy-preview-1984--replicated-docs-upgrade.netlify.app/vendor/helm-native-about#limitations
=> Add kustomize and helmchart v2 limitation

docs/partials/custom-resource-application/_kubectlVersion.mdx, docs/partials/custom-resource-application/_kustomizeVersion.mdx, docs/reference/custom-resource-application.mdx, docs/release-notes/rn-app-manager.md
https://deploy-preview-1988--replicated-docs.netlify.app/reference/custom-resource-application
=> Remove kubectl and kustomize version

docs/vendor/packaging-embedded-kubernetes.md
https://docs.replicated.com/vendor/packaging-embedded-kubernetes#include-a-kubernetes-installer-in-an-application-release-beta does not direct us to the correct place
=> chore: Update hyperlink

docs/vendor/packaging-include-resources.md
https://github.com/replicatedhq/replicated-docs/issues/2011
Preview: https://deploy-preview-2041--replicated-docs.netlify.app/vendor/packaging-include-resources#kotsioexclude
=> Fix quotes around annotations

docs/reference/kots-cli-get-config.md, docs/reference/kots-cli-set-config.mdx
- [SC-98393](https://app.shortcut.com/replicated/story/98393)
- [SC-99170](https://app.shortcut.com/replicated/story/99170)
- [SC-100008](https://app.shortcut.com/replicated/story/100008)
=> Document additional flags for the get/set config CLI commands

docs/vendor/releases-creating-customer.md
Story: https://app.shortcut.com/replicated/story/100337/allow-searching-customers-on-vendor-api-by-customer-email
=> Add customer email search to the docs

docs/intro-replicated.md
I had a hard time parsing this sentence:
```
Understand the state of an instance with access to telemetry, including application health, current running versions, and infrastructure and cluster details.
```
Suggested change:
```
Get insights into an instance's status by accessing telemetry data, which covers the health of the application, the versions that are currently running, and details about the infrastructure and clusters.
```
=> Update wording in intro-replicated.md

docs/vendor/custom-domains-using.md
Adds a warning about CAA records
=> Add a warning about CAA records in custom hostnames section

docs/vendor/custom-domains-using.md
=> Fix broken link on custom-domains-using.md

docs/reference/replicated-sdk-apis.md
Boolean value should not have quotes around it.
=> Remove quotes around boolean

docs/intro.md, docs/reference/replicated-cli-cluster-addon-create-object-store.md, docs/reference/replicated-cli-cluster-addon-create.md, docs/reference/replicated-cli-cluster-addon-ls.md, docs/reference/replicated-cli-cluster-addon-rm.md, docs/reference/replicated-cli-registry-add.mdx, docs/vendor/testing-about.md, docs/vendor/testing-cluster-addons.md, sidebars.js
From https://docs.google.com/document/d/1vzbEfUQrxR4LPzINlaqhNkkT5wbdUkG5b9sMyvZ2CwA/edit
=> docs(cmx): cluster add-ons

docs/reference/template-functions-license-context.md
Preview: https://deploy-preview-2255--replicated-docs.netlify.app/reference/template-functions-license-context#licensefieldvalue
=> Improve description of LicenseFieldValue

docs/partials/config/_property-when.mdx, docs/partials/config/_when-note.mdx, docs/partials/config/_when-requirements.mdx, docs/partials/config/_whenExample.mdx, docs/reference/custom-resource-config.mdx, docs/vendor/config-screen-conditional.mdx
https://deploy-preview-2257--replicated-docs.netlify.app/reference/custom-resource-config#when
=> Update requirements and limitations of config when property

docusaurus.config.js
=> add bash to supported languages

.github/workflows/vendor-portal-release-notes.yml
https://app.shortcut.com/replicated/story/102398/don-t-create-a-release-notes-pr-when-there-are-no-release-notes
=> Don't generate release notes PR if there are none

docs/reference/template-functions-static-context.md
* Add `embedded-cluster` and `k0s`
* Sort the list alphabetically
=> chore: Update detected k8s distributions

sidebars.js
TL;DR
-----
Updates sidebard with "Protecting Your Assets" lab
Details
-------
Incorporates the new licensing focused lab "Protecting Your Assets"
into the labs section of the navigation. This lab takes the learner
through the following lesssions:
1. What is the Replicated license?
2. Creating a customer and their license.
3. Using the Replicated proxy registry to protect your private images.
4. Using license Helm values in your templatess.
5. Custom license entitlements
6. Validating license entitlements with the Replcated SDK
7. Sending custom metrics to measure license usage
=> Adds licensing lab

docs/enterprise/snapshots-restoring-full.md, docs/enterprise/snapshots-restoring-full.mdx, docs/enterprise/snapshots-understanding.md, docs/enterprise/snapshots-understanding.mdx, docs/partials/snapshots/_limitation-cli-restores.mdx, docs/partials/snapshots/_limitation-dr.mdx, docs/partials/snapshots/_limitation-install-method.mdx, docs/partials/snapshots/_limitation-os.mdx, docs/partials/snapshots/_restore-types.mdx, docs/partials/snapshots/_step-get-backups.mdx, docs/partials/snapshots/_step-restore.mdx
About Backup and Restore: https://deploy-preview-2355--replicated-docs-upgrade.netlify.app/enterprise/snapshots-understanding
Restoring from Backups: https://deploy-preview-2355--replicated-docs-upgrade.netlify.app/enterprise/snapshots-restoring-full
=> Clarifying the limitations of restoring from full versus partial snapshots

docs/vendor/embedded-overview.mdx
Reverts replicatedhq/replicated-docs#2125
=> Revert "HOLD FOR RELEASE add airgap to embedded-cluster"

docs/vendor/replicated-sdk-slsa-validating.md, sidebars.js
Add new doc on how to validate SLSA attestations for the Replicated SDK
=> Add doc on how to validate SLSA attestations for the Replicated SDK

docs/reference/replicated-sdk-apis.md
Updates the SDK API example responses for changes made in https://github.com/replicatedhq/replicated-sdk/pull/186
=> update SDK API endpoint example responses

docs/vendor/embedded-overview.mdx
I'm fine if this deserves its own section or should be worded differently. Just wanted to be sure to capture it.
=> Say how to download a specific version

docs/reference/replicated-sdk-apis.md, docs/vendor/custom-metrics.md
Update docs for Custom Metrics `PATCH` and `DELETE` endpoint
=> Update docs for new custom metrics endpoint functionality

docs/vendor/team-management-rbac-configuring.md
Preview: https://deploy-preview-2450--replicated-docs.netlify.app/vendor/team-management-rbac-configuring#about-rbac-policies
=> add copy about the sales and support policies for enterprise plan

docs/vendor/team-management-saml-auth.md
https://deploy-preview-2458--replicated-docs.netlify.app/vendor/team-management-saml-auth
=> Clarify SAML login experience

docs/vendor/testing-about.md
There were a few missing limitations (airgap, arm, gpu). Have added those
=> Updating CMX limitations

docs/vendor/testing-supported-clusters.md
Add 1.30 to EKS
Move RKE2 to beta
=> Update CMX versions

docs/vendor/embedded-overview.mdx
https://deploy-preview-2493--replicated-docs-upgrade.netlify.app/vendor/embedded-overview#set-ip-address-ranges-for-pods-and-services
=> Add CIDR flag docs

docs/vendor/testing-ingress.md
This feature is in beta at this point, so updating docs accordingly
=> Relabel tunnels feature from alpha to beta

docs/vendor/private-images-replicated.mdx
https://deploy-preview-2499--replicated-docs.netlify.app/vendor/private-images-replicated#limitations
=> Add Replicated registry limitations

docs/partials/embedded-cluster/_requirements.mdx, docs/vendor/embedded-overview.mdx
https://deploy-preview-2509--replicated-docs.netlify.app/vendor/embedded-overview#requirements
https://deploy-preview-2509--replicated-docs.netlify.app/vendor/embedded-overview#host-preflight-checks
=> Update EC requirements

docs/reference/custom-resource-config.mdx
add warning about storing secrets in a text field
=> add warning about storing secrets in a text field

docs/partials/cmx/_billing.mdx, docs/partials/cmx/_prerequisites.mdx
Related story: https://app.shortcut.com/replicated/story/108018/make-the-stripe-payment-option-default-available-for-any-contracted-customers
Pages:
- https://deploy-preview-2512--replicated-docs.netlify.app/vendor/testing-how-to#prerequisites
- https://deploy-preview-2512--replicated-docs.netlify.app/vendor/testing-about#billing-and-credits
=> [HOLD TO MERGE] update credit purchasing/requesting docs for CMX

docs/vendor/testing-supported-clusters.md
May need to add more specific pricing detail here in the future, but that was getting a bit content heavy. To start let's just be clear which versions are in this "Extended Support EKS" category
=> Specifically call out EKS Extended Support Versions

docs/vendor/custom-domains-using.md
We have now added ability to use HTTP tokens for domain validation. TXT records may still be used, but if they are not displayed, there is no action that need from the user.
=> TXT records are now optional

docs/vendor/support-host-support-bundles.md
Add a warning about storing support bundles on public shares
=> add info warning about storing support bundles on public shares

docs/vendor/licenses-adding-custom-fields.md
https://deploy-preview-2548--replicated-docs.netlify.app/vendor/licenses-adding-custom-fields
=> Add max license field value size

docs/partials/image-registry/_image-registry-settings.mdx
https://deploy-preview-2558--replicated-docs.netlify.app/enterprise/image-registry-settings#configure-private-registries-in-online-clusters
=> Define registry namespace with example

docs/enterprise/updating-kurl.mdx
https://deploy-preview-2557--replicated-docs.netlify.app/enterprise/updating-kurl#update-the-kurl-cluster
=> Clarify kurl cluster update steps

docs/vendor/testing-supported-clusters.md
Adding supported instance types for AKS in CMX
=> sc-110032: Updating supported instance types for AKS

docs/reference/custom-resource-application.mdx
https://deploy-preview-2573--replicated-docs.netlify.app/reference/custom-resource-application#ports
=> Update support for go templates for ports key

docs/partials/embedded-cluster/_requirements.mdx
Totally fine if you want to tweak the wording. I just drafted this quickly.
=> Add EC connectivity reqs

docs/vendor/embedded-overview.mdx
https://deploy-preview-2592--replicated-docs.netlify.app/vendor/embedded-overview#install-behind-a-proxy-server
=> Clarify --no-proxy

docs/vendor/releases-share-download-portal.md
Updated generating Download Portal password section to match the new UI
=> Updated download portal password instructions

docs/vendor/testing-supported-clusters.md
Extending OKE support for standard3 Flex instances.
=> sc-106314: Update testing-supported-clusters.md for new OKE instance types

docs/reference/embedded-config.mdx
=> newer version of EC

docs/partials/replicated-sdk/_dependency-yaml.mdx, docs/release-notes/rn-replicated-sdk.md
Release notes for Replicated SDK 1.0.0-beta.29
=> Release notes for Replicated SDK 1.0.0-beta.29

docs/release-notes/rn-replicated-sdk.md
Release diff https://github.com/replicatedhq/replicated-sdk/compare/1.0.0-beta.29...317c7c4
=> Release notes for Replicated SDK 1.0.0-beta.30

docusaurus.config.js
=> Remove Qualified scripts

yarn.lock
Grabbed the easy and low risk updates from `npm audit fix`
=> Update packages from `npm audit fix`

docs/partials/support-bundles/_ec-support-bundle-intro.mdx, docs/partials/support-bundles/_generate-bundle-ec.mdx, docs/vendor/embedded-overview.mdx, docs/vendor/support-bundle-embedded.mdx, docs/vendor/support-bundle-generating.mdx
this is a temporary PR as XXX needs to be replaced with the actual embedded-cluster version yet to be released.
=> doc: document embedded-cluster support-bundle command

docs/vendor/customer-reporting.md
https://github.com/replicatedhq/replicated-docs/issues/2874
=> Fix inaccurate customer reporting stem sentence

docs/vendor/embedded-overview.mdx
Trying to make this less scary ("no automatic migration") and encourage vendors to reach out. https://replicated.slack.com/archives/C03PLT4SSTU/p1733519878143929?thread_ts=1733518866.538019&cid=C03PLT4SSTU
=> Change no kURL migration limitation

docs/reference/replicated-sdk-apis.md
Docs for new API: https://github.com/replicatedhq/replicated-sdk/pull/231
=> Docs for /api/v1/app/status API

docs/release-notes/rn-replicated-sdk.md
=> Replicated SDK 1.0.0 release notes

docs/release-notes/rn-app-manager.md
Story details: https://app.shortcut.com/replicated/story/117029
=> feat: [sc-117029] Add keep annotation to KOTS

docs/release-notes/rn-app-manager.md
The restore doesn't work this way for snapshots (it will be DR)
=> Remove orLabelSelectors because it doesn't work

docs/release-notes/rn-app-manager.md, docs/vendor/helm-native-v2-using.md, docs/vendor/helm-v2-migrate.md
https://deploy-preview-3004--replicated-docs.netlify.app/vendor/helm-v2-migrate#usehelminstall-false-limitation
=> Update useHelmInstall: false migration limitation

.github/dependabot.yml
minor updates to dependabot config
=> minor updates to dependabot config

docs/vendor/embedded-overview.mdx
the wording here is probably bad, but i didn't know what to say and didn't want to spend too much tine thinking about it. please change it.
=> add migration doc

docs/vendor/tutorial-kots-helm-create-release.md
=> make link match the page header

docs/reference/embedded-config.mdx
Make limitations a bulleted list
=> chore: update the limitation in the embedded config
