replicatedhq/replicated-docs

- docs/release-notes/rn-app-manager.md
- docs/release-notes/rn-kubernetes-installer.md
SC: https://app.shortcut.com/replicated/story/44108/friday-3-4-add-a-link-to-the-app-manager-and-kubernetes-installer-rns-topics-to-point-to-older-notes
/release-notes/rn-app-manager
/release-notes/rn-kubernetes-installer
> 44108 add links back to kots and kurl for earlier RNs

- docs/reference/replicated-cli-channel-disable-semver.md
- docs/reference/replicated-cli-channel-enable-semver.md
- docs/vendor/releases-semantic-versioning.md
- docs/vendor/releases-understanding.md
- sidebars.js
SC cards:
- Enabling semver content: https://app.shortcut.com/replicated/story/44393/content-diff-update-semver-docs
- Adds semver replicated CLI commands: https://app.shortcut.com/replicated/story/44507/migrate-replicated-cli-semver-commands
https://deploy-preview-200--replicated-docs.netlify.app/vendor/releases-understanding
https://deploy-preview-200--replicated-docs.netlify.app/vendor/releases-semantic-versioning
https://deploy-preview-200--replicated-docs.netlify.app/reference/replicated-cli-channel-enable-semver and https://deploy-preview-200--replicated-docs.netlify.app/reference/replicated-cli-channel-disable-semver
> 44393 adds semver topics

- docs/release-notes/rn-app-manager.md
- docs/release-notes/rn-kubernetes-installer.md
https://app.shortcut.com/replicated/story/44614/limit-heading-level-to-2-on-release-notes-topics
https://deploy-preview-209--replicated-docs.netlify.app/release-notes/rn-app-manager
https://deploy-preview-209--replicated-docs.netlify.app/release-notes/rn-kubernetes-installer
> 44614 limits heading level to 2 on rns

- docs/vendor/tutorial-installing-without-existing-cluster.md
Based on the host preflight check this disk space requirement should be 50GB instead of 40GB. I am not sure whether this is also an issue for installing it into an existing cluster
`[PASS] Longhorn Disk Usage: The disk containing directory /var/lib/longhorn has at least 50Gi of total space and is less than 60% full`
> Tutorial update disk space requirement

- docs/enterprise/image-registry-embedded-cluster.md
- docs/enterprise/updating-embedded-cluster.md
- docs/enterprise/updating-existing-cluster.md
- docs/reference/kots-cli-getting-started.md
- docs/vendor/packaging-ingress.md
- docs/vendor/tutorial-installing-with-existing-cluster.md
Rather then "embedded cluster" or "Kubernetes installer cluster"
> Use "Kubernetes installer-created" terminology

- docs/enterprise/installing-embedded-cluster.md
- docs/enterprise/installing-existing-cluster-online.md
- docs/enterprise/updating-embedded-cluster.md
SC: https://app.shortcut.com/replicated/story/32090/ability-to-install-a-specific-prior-app-version-for-embedded-and-existing-cluster-online-installs
Previews:
- https://deploy-preview-236--replicated-docs.netlify.app/enterprise/installing-existing-cluster-online#install-with-the-app-manager
- https://deploy-preview-236--replicated-docs.netlify.app/enterprise/installing-embedded-cluster
> [1.67.0] 32090: Add info about appVersionLabel to enterprise install docs

- docs/enterprise/installing-embedded-cluster.md
kurl airgap bundles have a .tar.gz extension, not .airgap
> .airgap is not a thing for kURL

- docs/enterprise/installing-existing-cluster-requirements.md
- docs/reference/custom-resource-application.md
- docs/vendor/packaging-rbac.md
- docs/vendor/preflight-support-bundle-creating.md
- docs/vendor/tutorial-installing-with-cli.md
- docs/vendor/tutorial-installing-with-existing-cluster.md
SC: https://app.shortcut.com/replicated/story/45428/add-the-supportsminimalrbacprivileges-feature
Previews: 
- https://deploy-preview-262--replicated-docs.netlify.app/enterprise/installing-existing-cluster-requirements
- https://deploy-preview-262--replicated-docs.netlify.app/vendor/packaging-rbac#namespace-scoped-access
- https://deploy-preview-262--replicated-docs.netlify.app/vendor/tutorial-installing-with-existing-cluster#install-the-application
- https://deploy-preview-262--replicated-docs.netlify.app/vendor/tutorial-installing-with-cli#install-the-application
- https://deploy-preview-262--replicated-docs.netlify.app/reference/custom-resource-application#requireminimalrbacprivileges
- https://deploy-preview-262--replicated-docs.netlify.app/reference/custom-resource-application#support …
> [1.68.0] 45428: Add `supportsMinimalRBACPrivilege` feature

- docs/enterprise/snapshots-storage-destinations.md
SC: https://app.shortcut.com/replicated/story/45921/blue-team-add-ca-certificate-upload-info-to-snapshots-docs
Preview: https://deploy-preview-270--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations
> Blocked on Release - 45921: Add CA Cert field to Snapshots Docs

- docs/enterprise/installing-embedded-cluster.md
SC: https://app.shortcut.com/replicated/story/46371/airgapped-install-instructions-not-abstract-about-slug-name
Replaced the example text in a few places:
- The original request: https://deploy-preview-296--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#install-in-an-air-gapped-environment
- Also: https://deploy-preview-296--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#install-in-an-online-environment
- Also: https://deploy-preview-296--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#install-with-high-availability
> 46371 clarify examples in commands

- README.md
https://app.shortcut.com/replicated/story/43877/ability-to-view-larger-size-screenshots-within-doc-site
Updated the wiki here: https://wiki.replicated.io/doc/graphics-06qYq8Vfq7#h-include-a-link-to-larger-versions-of-graphics
> 43877 adds info about viewing large imgs

- docs/enterprise/installing-existing-cluster-airgapped.md
SC: https://app.shortcut.com/replicated/story/46045/incorrect-info-in-air-gap-install-instructions-for-existing-cluster
https://deploy-preview-308--replicated-docs.netlify.app/enterprise/installing-existing-cluster-airgapped#push-images-and-install-the-admin-console
> 46045 Clarify the difference between kotsadm bundle & airgap bundle

- docs/vendor/offsite-backup.md
We updated the diagram but kept the references to enterprise buckets. That could infer enterprise vendors are treated differently. This isn't true, only 'add-on' vendors are treated differently.
> Removed enterprise bucket references & added info

- docs/enterprise/snapshots-restoring-full.md
The flag to use with the `velero install` command is `--use-restic` per [Velero docs](https://velero.io/docs/main/restic/#install-restic).
Otherwise, will get the error: `An error occurred: unknown flag: --restic`
> --use-restic flag when installing velero

- docs/reference/kots-cli-getting-started.md
Adds uninstall instructions for the kots cli: https://app.shortcut.com/replicated/story/48871/how-to-uninstall-the-kots-cli
https://deploy-preview-370--replicated-docs.netlify.app/reference/kots-cli-getting-started#uninstall
> 48871 add uninstall instructions

- docs/vendor/admin-console-customize-app-icon.md
https://app.shortcut.com/replicated/story/40570/resolve-discrepancy-between-text-and-yaml-file-in-the-customizing-app-icon-topic
Picked this up because we'll be updating this topic for the new "preview the app icon" feature that's coming out, so I wanted to get this odd discrepancy resolved and the topic cleaned up so that it's easier to add in the updates. 
https://deploy-preview-372--replicated-docs.netlify.app/vendor/admin-console-customize-app-icon
> 40570 remove outdated info about descriptor key

- docs/enterprise/troubleshooting-an-app.md
This PR should fix an issue where the triple backtick syntax to create code blocks is displayed in the command for creating a support bundle. Using the copy button currently copies these backticks along with the command.
> Remove code block syntax in command

- .github/workflows/algolia-crawl.yml
Add a manual trigger to the search scrape job so that it can be manually run without a PR merge while we investigate a better solution.
> Add manual trigger to scrape job

- docs/enterprise/installing-embedded-cluster.md
SC: https://app.shortcut.com/replicated/story/51930/embedded-cluster-install-procedure-missing-kots-install-command-for-air-gap
Preview: https://deploy-preview-444--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#install-in-air-gapped-environments
> 51930: Added Admin Console Install steps to Air Gap Install Section

- sidebars.js
Adds an external link to the Security at Replicated page on the marketing site in the Policies section of the docs site.
> Adds link to Security at Replicated webpage in Policies section

- docs/release-notes/rn-kubernetes-installer.md
- docs/vendor/distributing-workflow.md
- docs/vendor/packaging-rbac.md
- docs/vendor/preflight-support-bundle-creating.md
- docs/vendor/tutorial-installing-air-gap-existing-cluster-gcp.md
- docs/vendor/tutorial-installing-air-gap.md
- docs/vendor/tutorial-installing-with-cli.md
- docs/vendor/tutorial-installing-with-existing-cluster.md
- docs/vendor/tutorial-installing-without-existing-cluster.md
SC: https://app.shortcut.com/replicated/story/41574/content-gap-make-it-easy-for-vendors-to-understand-host-preflights-and-how-to-customize-them-as-part-of-kubernetes-installer
Previews: 
- https://deploy-preview-428--replicated-docs.netlify.app/vendor/preflight-support-bundle-creating#about-host-preflight-checks-for-kubernetes-installers
- https://deploy-preview-428--replicated-docs.netlify.app/vendor/distributing-workflow#iterating-your-releases
- https://deploy-preview-428--replicated-docs.netlify.app/vendor/packaging-rbac#strict-preflight-checks
- https://deploy-preview-428--replicated-docs.netlify.app/vendor/tutorial-installing-without-existing-cluster#install-the-application
- https://deploy-preview-428--replicated-docs.netlify.app/vendor/tutorial-installing-with-existing-cluster#ins …
> 41574: Adding Host Preflight Checks

- docs/release-notes/rn-app-manager.md
1.76.0 was showing before 1.76.1.  This PR moves 1.76.1 to the top.
> fix release ordering for v1.76.1

- docs/vendor/helm-install.md
https://app.shortcut.com/replicated/story/52694/document-how-to-deliver-the-admin-console-when-offering-direct-helm-install
I based this new section and procedure off these instructions that Marc wrote: https://docs.google.com/document/d/1P4oCUtkM8IileNNw83NepEsyq14rTTS9w-64T-uwmeA/edit#heading=h.lfu2nj4y975g
Preview: [/vendor/helm-install#deliver-admin-console](https://deploy-preview-480--replicated-docs.netlify.app/vendor/helm-install#deliver-admin-console)
> Add procedure for delivering admin console

- .github/workflows/algolia-crawl.yml
Add a concurrency group to prevent the scrape jobs from walking on each other
> [sc-49457] prevent scrape jobs from walking on each other

- docs/enterprise/snapshots-configuring-hostpath.md
- docs/enterprise/snapshots-configuring-nfs.md
**Stories**:
- https://app.shortcut.com/replicated/story/54086/clarify-user-group-permissions-1001-1001-for-hostpath-and-nfs-destinations
- https://app.shortcut.com/replicated/story/54087/add-more-detail-to-hostpath-limitations
**Previews**: 
NFS Requirements: https://deploy-preview-484--replicated-docs.netlify.app/enterprise/snapshots-configuring-nfs#requirements
Host Path Requirements: https://deploy-preview-484--replicated-docs.netlify.app/enterprise/snapshots-configuring-hostpath#requirements
> Add user group permission requirements for Host Path and NFS destinations

- docs/vendor/releases-promoting.md
Adding a note to the required releases section to indicate the KOTS version that this was released in.  I did not see an area where this was explicitly specified outside of the release notes.
> add version for required releases

- docs/enterprise/snapshots-understanding.md
- docs/vendor/snapshots-overview.md
- sidebars.js
**Story**: https://app.shortcut.com/replicated/story/54106/replace-snapshots-in-titles-and-headings-with-backup-and-restore 
According to this request from the support team, users are struggling to find information about backup and restore in the docs because they don't know what "snapshot" means. We should rename this in the TOC, titles, and headings to make it easier to find, while explaining the snapshots is the name of the feature in the page content.
**Previews**:
Edited some of the titles/headings in this section of the vendor docs: https://deploy-preview-489--replicated-docs.netlify.app/vendor/snapshots-overview
Also edited titles/headings in these enterprise docs (some light rewording in the content of the topics as well. I couldn't resist): …
> Replace "snapshots" with "Backup and Restore"

- docs/enterprise/snapshots-troubleshooting-backup-restore.md
https://app.shortcut.com/replicated/story/54091/document-workaround-for-patching-the-velero-deployment-to-edit-restic-timeout
See the Timeout Error section: https://deploy-preview-494--replicated-docs.netlify.app/enterprise/snapshots-troubleshooting-backup-restore#timeout-error-when-creating-a-snapshot
I also did some reformatting to use the Symptom/Cause/Solution format
> Add timeout troubleshooting description

- docs/vendor/helm-install.md
Story: https://app.shortcut.com/replicated/story/54157/add-procedure-for-using-private-images-to-alpha-topic
Preview: https://deploy-preview-485--replicated-docs.netlify.app/vendor/helm-install#private-images
I based this procedure on the [Example: Delivering Image Pull Secrets for Private Images](https://docs.replicated.com/vendor/helm-install#example-delivering-image-pull-secrets-for-private-images) content that is in the currently-published version of this topic. I also used the generic procedure provided in the [Helm Installation (Alpha)](https://docs.google.com/document/d/1P4oCUtkM8IileNNw83NepEsyq14rTTS9w-64T-uwmeA/edit#heading=h.l11cvyaz20lx) google doc.
> Add procedure for using private registry

- docs/reference/custom-resource-application.md
- docs/vendor/policies-vulnerability-patch.md
In our next version of KOTS, we plan to upgrade to the latest version of kustomize, because the performance degradation from our current version seems to be acceptably small. This new version resolves all current CVEs, so we can remove this section from our docs that lists out the CVEs we exepted for kustomize.
FYI @tcalotta
> Remove kustomize CVE exceptions after upgrade to v4

- docs/vendor/packaging-private-images.md
Removed the section that states that images and digests cannot be used together.  Also added an additional sentence after the online digest support piece to indicate that both can be used together for online installations (except for those configured to use an internal private registry).
> HOLD FOR RELEASE update support for image tags and digests

- docs/vendor/helm-install.md
Moves the old "Requirement" section to the top, and renames it "Prerequisite". Adds a link in this section to the topic that describes how to add a helm chart to a release, so users can find this info more easily.
Story: https://app.shortcut.com/replicated/story/56107/tell-users-how-to-get-started-packaging-a-helm-chart-in-the-alpha-topic
Preview: https://deploy-preview-538--replicated-docs.netlify.app/vendor/helm-install#prerequisite
> How to add helm charts to releases

- docs/vendor/tutorial-installing-without-existing-cluster.md
Provided updates to clear up some confusing bits in the embedded tutorial, specifically around the getting started steps. These are recommendations, won't be surprised if some or all or rejected! Hope it's helpful.
- Condense instruction about using GCP and note about using other providers to a single instruction, avoids recommending GCP above others and helps clarify that all methods work equally
- Remove extra steps from install instructions. The output from kurl install is translated into steps in the tutorial, but this is a hand holding walkthrough and some steps are out of scope, and are also printed verbatim in the kurl install output for users that want them:
- instructions to access Grafana
- instructions to add worker nodes
- Remove prompt from `kubectl get pods` command block - …
> update install instructions for embedded tutorial

- docs/vendor/team-management-rbac-resource-names.md
Story: https://app.shortcut.com/replicated/story/56279/add-missing-rbac-resource-names
Preview: https://deploy-preview-566--replicated-docs.netlify.app/vendor/team-management-rbac-resource-names#kotsappappidinstallers
> add installers rbac policies

- docs/reference/kots-cli-velero-index.md
- sidebars.js
SC: https://app.shortcut.com/replicated/story/57161/add-list-of-kots-cli-configure-commands-to-the-main-velero-section
Preview: https://deploy-preview-594--replicated-docs.netlify.app/reference/kots-cli-velero-index
> 57161: Added a list of supported `kots velero` commands

- docs/enterprise/installing-general-requirements.md
SC: https://app.shortcut.com/replicated/story/56781/kubernetes-version-compatibility-table-should-not-include-unsupported-k8s-version
Preview: https://deploy-preview-597--replicated-docs.netlify.app/enterprise/installing-general-requirements#kubernetes-version-compatibility
> 56781: Updated Kubernetes Version Compatibility Table

- docs/reference/kots-cli-install.md
SC: https://app.shortcut.com/replicated/story/56888/all-flags-in-the-cli-reference-should-include-information-on-the-default
Preview: https://deploy-preview-599--replicated-docs.netlify.app/reference/kots-cli-install#usage
> Added default values to kots CLI install reference info

- docs/enterprise/auth-identity-provider.md
- docs/enterprise/installing-app-setup.md
SC: https://app.shortcut.com/replicated/story/57300/enterprise-identity-service-docs-should-mention-how-to-configure-the-hostname-for-the-admin-console
Previews:
- https://deploy-preview-612--replicated-docs.netlify.app/enterprise/auth-identity-provider#prerequisites
- https://deploy-preview-612--replicated-docs.netlify.app/enterprise/installing-app-setup#access-the-admin-console-and-deploy-the-application
> 57300: Hostname field required for Identity Service

- docs/vendor/helm-release.md
The indentation is was missing, causing the example not perceived well by the vendor portal resulting into errors.
> Fixing the indentation on the sample YAML

- docs/intro.md
- docs/vendor/config-screen-about.md
- docs/vendor/config-screen-map-inputs.md
- docs/vendor/database-config-adding-options.md
- docs/vendor/distributing-workflow.md
- docs/vendor/packaging-private-images.md
- docs/vendor/repository-workflow-and-tagging-releases.md
- docs/vendor/tutorial-adding-db-config.md
- docs/vendor/tutorial-ci-cd-integration.md
- docs/vendor/tutorial-ecr-private-images.md
- docs/vendor/tutorial-ha-cluster-deploying.md
- docs/vendor/tutorial-installing-air-gap-existing-cluster-gcp.md
- docs/vendor/tutorial-installing-air-gap.md
- docs/vendor/tutorial-installing-with-cli.md
- docs/vendor/tutorial-installing-with-existing-cluster.md
- docs/vendor/tutorial-installing-without-existing-cluster.md
- docs/vendor/vendor-portal-creating-account.md
- sidebars.js
Story: https://app.shortcut.com/replicated/story/57808/remove-separate-tutorials-section
Detailed description of all the changes made in this comment on the story: https://app.shortcut.com/replicated/story/57808/remove-separate-tutorials-section#activity-58194
Topics for review:
- Welcome topic updated to include Get Started with Replicated section: https://deploy-preview-619--replicated-docs.netlify.app/
- Getting started section renamed and moved to top, and tutorials re-titled: https://deploy-preview-619--replicated-docs.netlify.app/vendor/tutorial-installing-without-existing-cluster
- ECR tutorial moved: https://deploy-preview-619--replicated-docs.netlify.app/vendor/tutorial-ecr-private-images
- Adding db options tutorial moved to a new section in Packaging named Adding Persistent …
> Remove separate Tutorials section

- docs/vendor/licenses-referencing-fields.md
https://app.shortcut.com/replicated/story/58428/incorrect-api-version-on-preflight-example
Also noticed that the code sample did not specify `yaml`, so I updated that too.
Preview: https://deploy-preview-628--replicated-docs.netlify.app/vendor/licenses-referencing-fields#example-reference-a-custom-license-field-in-a-preflight-check
> Correct the api version for Preflight example

- docs/vendor/tutorial-ha-cluster-deploying.md
- docs/vendor/tutorial-installing-air-gap-existing-cluster-gcp.md
- sidebars.js
https://app.shortcut.com/replicated/story/58652/remove-advanced-tutorials-from-the-vendor-docs
> Removes advanced tutorials from TOC

- docs/enterprise/installing-embedded-cluster.md
SC: https://app.shortcut.com/replicated/story/58430/air-gap-install-on-embedded-cluster-procedure-incorrect
Previews:
-https://deploy-preview-640--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#air-gap
- https://deploy-preview-640--replicated-docs.netlify.app/enterprise/installing-embedded-cluster#install-with-ha-in-air-gapped-environments
> 58430: Corrected Air Gap Installation Info

- docs/reference/kots-lint.md
- sidebars.js
This PR provides initial documentation for [all 40 kots-lint rules](https://github.com/replicatedhq/kots-lint/blob/77505d6f7077a2b73c28efc69489645e15c7a928/pkg/kots/rego/kots-spec-opa-nonrendered.rego).
Using eslint docs as prior art: https://eslint.org/docs/latest/rules/
**Preview of this page:** https://deploy-preview-645--replicated-docs.netlify.app/reference/kots-lint
> add initial kots lint rules list

- docs/release-notes/rn-app-manager.md
Document this known issue in the release notes, including workarounds: https://app.shortcut.com/replicated/story/59762/kots-icons-are-huge-on-firefox-browser
Docs story: https://app.shortcut.com/replicated/story/59849/known-issue-for-firefox-bug
Preview: Warning note at the top of the 1.86.0 release and a new Known Issue section https://deploy-preview-673--replicated-docs.netlify.app/release-notes/rn-app-manager#1860
> firefox known issue

- docs/reference/kots-lint.mdx
This PR adds information to the kots lint rules page on how to configure lint rules levels. 
Part of [SC-59102](https://app.shortcut.com/replicated/story/59102/kots-lintconfig).
> add information about lint-config to kots lint rules page

- docs/reference/custom-resource-application.md
- docs/vendor/admin-console-prometheus-monitoring.md
Updated example to include a working version of our default graphs using template functions.  This depends on the changes in [this PR](https://github.com/replicatedhq/kots/pull/3284), so we should hold off merging until the next KOTS release.
[SC-59379](https://app.shortcut.com/replicated/story/59379/fmt-sprintf-usage-broken-for-custom-graph-queries)
> HOLD FOR RELEASE - fix custom graph example

- docs/reference/custom-resource-preflight.md
The text for `exclude` logic in preflights and support bundles is backwards.
> Fix description of `exclude` logic

- .github/workflows/app-manager-release-notes.yml
This PR updates the automated release notes PR to reflect the currently supported k8s versions of 1.21 through 1.25
> update supported k8s versions for app manager automated release notes

- docs/vendor/packaging-using-tls-certs.md
SC: https://app.shortcut.com/replicated/story/59979/remove-the-kots-specific-tls-certs-content-from-kurl-sh
This is just part one of this SC card - just adding the ECKO add-on info for the self-signed cert renewal. The removal of the kURL content will happen in another PR in the kURL repo.
Preview: https://deploy-preview-716--replicated-docs.netlify.app/vendor/packaging-using-tls-certs
> 59979: Added renewal clarification

- docs/intro-replicated.md
Story: https://app.shortcut.com/replicated/stories/space/37255/documentation-team-view
Preview: https://deploy-preview-719--replicated-docs.netlify.app/intro-replicated
Removes the confusing open source section and redistributes the relevant info from that section accordingly. (Additional edits to the Replicated Features section to be done as part of a different story)
> Remove Open Source Tools section from What Is Replicated

- docs/vendor/licenses-about.md
This PR adds a sentence to explain that a license will expire at midnight UTC on the date selected in the vendor portal.  This supports https://github.com/replicatedhq/kots/pull/3380 for [SC-59063](https://app.shortcut.com/replicated/story/59063/can-t-check-for-updates-because-license-is-expired-but-neither-the-admin-console-nor-vendor-portal-says-it-is-expired-yet).
*No need to wait until release to merge this, as this is how the vendor portal behaves today.*
> add clarity around license expiration date

- docs/vendor/distributing-workflow.md
- docs/vendor/tutorial-adding-db-config.md
- docs/vendor/tutorial-ci-cd-integration.md
- docs/vendor/tutorial-ecr-private-images.md
- docs/vendor/tutorial-ha-cluster-deploying.md
- docs/vendor/tutorial-installing-air-gap-existing-cluster-gcp.md
- docs/vendor/tutorial-ui-create-new-version.md
- docs/vendor/tutorial-ui-update-app.md
- docs/vendor/vendor-portal-creating-account.md
- docusaurus.config.js
Did an `ag` to find all the places where we still use the old tutorial links. Updated these links to use the new xrefs instead so that they are not relying on redirects.
https://app.shortcut.com/replicated/story/61504/replace-all-links-to-the-old-tutorial-topics
> 61504: Update links to tutorials

- docs/vendor/team-management-github-username.md
Corrects a small typo in "role-based access control" (previously "roll-based").
> Fixes typo in collab repo access docs

- docs/partials/kots-lint-rules/_invalid-yaml.mdx
- docs/partials/kots-lint-rules/_invalid_type.mdx
- docs/reference/kots-lint.mdx
This PR adds these missing rules to the [KOTS lint docs page](https://docs.replicated.com/reference/kots-lint):
- helm-archive-missing
- helm-chart-missing
- invalid-yaml
- invalid_type
Related story: https://app.shortcut.com/replicated/story/61334/add-docs-for-missing-linter-rules
> add helm-chart-missing and helm-archive-missing lint rules

- docs/enterprise/installing-existing-cluster-automation.md
Story: https://app.shortcut.com/replicated/story/46286/confusing-directions-in-headless-installation
Fixing inaccurate statement that says you can access the admin console at port 8800 after running with --no-port-forward. Instead, you can run `kubectl kots admin-console --namespace NAMESPACE` to start the admin console if you want
Preview: https://deploy-preview-779--replicated-docs.netlify.app/enterprise/installing-existing-cluster-automation#disable-admin-console-port-forwarding
> Fix inaccuracy in headless install

- docs/reference/custom-resource-redactor.md
- docs/vendor/preflight-support-bundle-creating.md
Change https://github.com/replicatedhq/troubleshoot/pull/734 removes IPv4 address redaction by default.  This change removes that promise from the document, plus adds a little more disclaimer type info on the remaining redactors since the promise in the doc is more broad than the actual redactors can cover.
> Update notes on Redactors

- docs/partials/getting-started/_tutorial-intro.mdx
- docs/vendor/tutorial-cli-setup.mdx
- docs/vendor/tutorial-ui-setup.mdx
SC: https://app.shortcut.com/replicated/story/62155/update-tutorial-intro-to-remove-redundancies
Previews:
- https://deploy-preview-784--replicated-docs.netlify.app/vendor/tutorial-ui-setup
- https://deploy-preview-784--replicated-docs.netlify.app/vendor/tutorial-cli-setup
> 62155: Removed redundant statements from tutorial intros

- docs/vendor/helm-native-helm-install-order.md
Think that the weight number gives an error if it's in quotes
> Update helm-native-helm-install-order.md remove quotes from weight setting in docs

- docs/vendor/team-management-rbac-resource-names.md
SC: https://app.shortcut.com/replicated/story/62925/remove-multifactor-from-the-team-authentication-read-and-team-authentication-update-docs
Previews:
- https://deploy-preview-805--replicated-docs.netlify.app/vendor/team-management-rbac-resource-names#teamauthenticationupdate
- https://deploy-preview-805--replicated-docs.netlify.app/vendor/team-management-rbac-resource-names#teamauthenticationread
> 62925: Removed multifactor from two RBAC resources

- docs/vendor/tutorial-ui-install-app-manager.md
Fixes a typo in the `gcloud` command where it was shown as `glcloud`.
> Corrects a typo in the embedded cluster steps

- docs/reference/replicated-cli-release-create.md
https://github.com/replicatedhq/replicated-docs/issues/834 caught a copy/paste error on the description of release notes and version flags for the replicated CLI release create command.
> Fixes copy/paste error

- sidebars.js
Aligns with our new strategy of limiting words. (Feedback from JQ that I forgot to incorporate on previous PR: https://app.shortcut.com/replicated/story/64385/change-using-private-registries-to-private-registries)
> Edit section title to remove verb

- docs/vendor/policies-support-lifecycle.md
Now that it's past 12/31/22, these products need to be updated from EOA to EOL
> Move Swarm, Ship, AKA to EOL in support table

- docs/vendor/helm-optional-charts.md
Related to issue https://github.com/replicatedhq/replicated-docs/issues/868
Story: https://app.shortcut.com/replicated/story/65695/issue-868-deprecated-helm-chart-in-example
Preview: https://deploy-preview-872--replicated-docs.netlify.app/vendor/helm-optional-charts
> Replace link to deprecated chart

- docs/vendor/preflight-support-bundle-creating.md
SC: https://app.shortcut.com/replicated/story/59193/add-analyzer-example-to-support-bundle-content
Changed the scope of the SC ticket. Decided to simplify the complex request and docs by adding a link to the default kots support bundle spec.
Preview: https://deploy-preview-875--replicated-docs.netlify.app/vendor/preflight-support-bundle-creating#customize-a-support-bundle
> 59193: Adding link to default spec

- docs/partials/helm/_helm-cli-limitations.mdx
- docs/partials/helm/_helm-template-limitation.mdx
- docs/partials/helm/_native-helm-limitations.mdx
- docs/vendor/helm-install.md
- docs/vendor/helm-installing-native-helm.md
- docs/vendor/helm-overview.md
https://app.shortcut.com/replicated/story/60145/document-that-helm-functions-that-require-access-to-cluster-are-not-supported
Creates a new Limitations section that applies to both the Replicated helm deployment methods ("Replicated KOTS" and "Native Helm") & adds a new limitation about how Helm cannot access the cluster during rendering with the `helm template` command.
Previews (used a snippet so that this shows up in a couple places):
* Adds the new limitation to the existing list of Native Helm limitations: https://deploy-preview-877--replicated-docs.netlify.app/vendor/helm-installing-native-helm#native-helm-limitations
* Adds a new Limitations section in `helm-overview.md` that lists all limitations for all Helm install methods: …
> Add Replicated `helm template` limitation

- docs/vendor/preflight-host-preflights.md
There were a couple of syntax things in the host preflight example here that broken the kurl cluster deployment when I tested it today
Ref troubleshoot doc example: https://troubleshoot.sh/docs/host-collect-analyze/http/
> Fixing a couple of syntax items on hostpreflight examples

- docs/reference/kots-cli-install.md
this flag doesn't exist for the `kots install` command since the upstream-uri is provided as the first argument to the command.  the link instead takes you to a different page for the `upload` command: https://docs.replicated.com/reference/kots-cli-upload#usage
> remove reference to nonexistent `--upstream-uri` flag

- docs/vendor/packaging-rbac.md
SC: https://app.shortcut.com/replicated/story/31972/docs-kots-rbac-docs-are-wrong
The original SC story is outdated and the current conten is mainly correct, just the note really needed to be changed because kotsadm-operators are no longer used.
Preview: https://deploy-preview-903--replicated-docs.netlify.app/vendor/packaging-rbac#operators-and-multiple-namespaces
> 31972: Edit kotsadmin-operator info

- .github/workflows/app-manager-release-notes.yml
this PR updates the automated release notes action to reflect the currently supported k8s versions for the next kots release
> update supported k8s versions for app manager

- docs/vendor/packaging-installer-storage.md
https://app.shortcut.com/replicated/story/66707/rook-block-device-can-t-be-part-of-a-raid-configuration
Can merge pending technical approval of the same content to the kurl site in https://github.com/replicatedhq/kurl.sh/pull/934
> SC66707 Clarify block storage requirement for Rook

- docs/reference/kots-cli-getting-started.md
Updates the KOTS reference install section to include instructions on how and when to use the new env variables the install script reads `REPL_INSTALL_PATH` and `REPL_USE_SUDO`
> Update KOTS install reference to include new env variable options

- docs/reference/kots-cli-getting-started.md
https://app.shortcut.com/replicated/story/67365/kots-cli-docs-are-unclear-for-mac
Preview: https://deploy-preview-929--replicated-docs.netlify.app/reference/kots-cli-getting-started#manually-download-and-install
> Edit manual kots CLI install steps

- docs/vendor/packaging-ingress.md
Update ingress syntax to the [stable ingress API](https://kubernetes.io/docs/concepts/services-networking/ingress/)
The old syntax will cause: 
- "unknown field" errors for `serviceName` and `servicePort` fields
- "pathType is required" error for the missing `pathType` field
> fix: ingress syntax

- docs/enterprise/status-viewing-details.md
- docs/partials/status-informers/_statusesTable.mdx
- docs/vendor/admin-console-display-app-status.md
Add information about the new daemonset status informer to the vendor and enterprise "Displaying Application Status" pages.
This is needed due to [this KOTS PR](https://github.com/replicatedhq/kots/pull/3636)
Things I'm not sure about:
* Are the column widths in the status table distributed in a visually appealing way? Maybe the leftmost column should shrink so everything else can be wider.
* Calling the pods in the daemonset daemons. They're really pods that run on each node, but they're also not replicas in the deployment or statefulset sense.
> Add daemonset status informer info

- docs/enterprise/snapshots-creating.md
- docs/vendor/snapshots-configuring-backups.md
- docs/vendor/snapshots-overview.md
SC: https://app.shortcut.com/replicated/story/71228/clarify-how-volumes-are-backed-up
and SC: https://app.shortcut.com/replicated/story/38953/kots-snapshots-documentation-suggests-mentions-using-opt-in-for-volume-backups-which-only-works-with-restic
Using the same PR for both of these SC because they are closely related.
Also, note that one of the SC stories addresses an issue that a vendor opened here: https://github.com/replicatedhq/kots.io/issues/598
Previews:
- https://deploy-preview-995--replicated-docs.netlify.app/vendor/snapshots-overview#pod-volume-data
- https://deploy-preview-995--replicated-docs.netlify.app/vendor/snapshots-configuring-backups
> 71228: Pod Volume Backups

- docs/vendor/packaging-private-images.md
The example does not use the `--image` flag, which will result in the following:
```
$ replicated registry test index.docker.io my-company/my-image:v1.2.3
Error: required flag(s) "image" not set
```
With the flag, it runs the check, as expected:
```
$ replicated registry test index.docker.io --image my-company/my-image:v1.2.3
Registry conection appears ok
```
> fix cli registry test example

- docs/vendor/snapshots-overview.md
SC: https://app.shortcut.com/replicated/story/71899/correct-terminology-for-backups-snapshots
> 71899: Correction: Terminology edit backups v snapshots

- docs/vendor/team-management-rbac-resource-names.md
Adds the missing `kots/app/:id/license/:id/airgap/password` resource to the docs.
Related story: https://app.shortcut.com/replicated/story/72052/add-missing-airgap-password-rbac-resourced-to-docs
Preview: https://deploy-preview-1011--replicated-docs-upgrade.netlify.app/vendor/team-management-rbac-resource-names#kotsappappidlicenselicenseidairgappassword
> add kots/app/:id/license/:id/airgap/password rbac resource to docs

- docs/enterprise/monitoring-applications.md
- docs/enterprise/monitoring-external-prometheus.md
- sidebars.js
https://app.shortcut.com/replicated/story/71548/update-docs-on-how-to-consume-prometheus-metrics-externally
Preview: 
- New topic that explains how to consume metrics from the Prometheus service in k8s installer clusters: https://deploy-preview-1010--replicated-docs.netlify.app/enterprise/monitoring-external-prometheus
- Made some edits to this one and added a link to the new topic: https://deploy-preview-1010--replicated-docs.netlify.app/enterprise/monitoring-applications
> How to consume prometheus metrics externally

- docs/vendor/policies-vulnerability-patch.md
This PR removes an outdated section for MinIO vulnerability disclosures.  We updated to the latest version of MinIO in [KOTS 1.95.0](https://docs.replicated.com/release-notes/rn-app-manager#improvements-1-95-0), so we can remove these.
The entire section has been removed since it only had MinIO disclosures.  It's possible we want to keep the `## Vulnerability Management Exceptions` header, so open to suggestions here.
> remove outdated minio vulnerability disclosures

- docs/reference/custom-resource-lintconfig.mdx
- docs/reference/linter.mdx
Reverts replicatedhq/replicated-docs#1000
Now that https://github.com/replicatedhq/kots-lint/pull/142 is merged and deployed this functionality is supported again. The docs were updated to set expectations correctly while it was still broken.
Ref [sc-65163](https://app.shortcut.com/replicated/story/65163/lintconfig-doesn-t-affect-nonexistent-status-informer-object-warning)
I've tested the functionality myself and was satisfied it's working now :)
> Revert "Update custom-resource-lintconfig.mdx"

- docs/vendor/customer-reporting.md
- docs/vendor/licenses-about.md
As part of getting started on [the story to doc the adoption graph](https://app.shortcut.com/replicated/story/72696/insights-document-the-adoption-graph), I noticed that the content about the customer Reporting page was duplicated across both the "About Customers" and "Customer Reporting" topics. I wanted to clean this up before creating space to add in the new Adoption Graph content.
This PR moves the bulk of the content about customer reporting to the Customer Reporting topic, and adds a link to it from the About Customers topic.
- Some updates for style and to add a topic sentence in the Customer Reporting topic: https://deploy-preview-1050--replicated-docs.netlify.app/vendor/customer-reporting
- Removes the _About the Customer Reporting Page_ section from the About Customers topic and …
> Remove duplicate customer reporting info

- docs/vendor/helm-image-registry.md
Preview: https://deploy-preview-1062--replicated-docs.netlify.app/vendor/helm-image-registry (See the new section on supporting both types of installations. Also removed content in other sections to reduce noise and clutter)
Story: https://app.shortcut.com/replicated/story/73789/update-organization-to-reduce-noise-and-improve-skim-ability-of-the-using-private-registries-for-helm-cli-installations-topic
> Clarify steps to support both helm CLI and kots installations

- docs/enterprise/updating-app-manager.md
https://github.com/replicatedhq/replicated-docs/issues/1077
This PR:
- Clarifies that the commands listed will either update the kots CLI version _or_ install the kots CLI if it isn't already installed
- Adds a link to the Installing the kots CLI topic for more information (installing without root access, etc)
Preview: https://deploy-preview-1079--replicated-docs.netlify.app/enterprise/updating-app-manager#online-environments
> Issue #1077: Clarify kots CLI installation steps in the upgrade procedures

- docs/reference/custom-resource-config.md
https://app.shortcut.com/replicated/story/75137/kots-config-validation-failing-when-the-item-is-required-and-has-default-value-and-or-when-hidden
> item validation docs

- docs/enterprise/updating-embedded-cluster.md
- docs/partials/updating/_installerRequirements.mdx
- docs/partials/updating/_upgradePrompt.mdx
- docs/vendor/installer-history.md
https://app.shortcut.com/replicated/story/75353/edit-info-about-upgrading-k8s-by-more-than-2-minor-versions-for-kurl-clusters
**Enterprise docs updates**
Updated the Kubernetes Update section to explain how you can upgrade any number of minor versions at once: https://deploy-preview-1107--replicated-docs.netlify.app/enterprise/updating-embedded-cluster#kubernetes
Adds info about how you need to download a package for air gap Kubernetes upgrades of more than one minor version: https://deploy-preview-1107--replicated-docs.netlify.app/enterprise/updating-embedded-cluster#kubernetes-multi
Add a note to the air gap upgrade procedure to describe how the script looks for the assets and prints a command to download them if they can't be found: …
> Update kURL upgrade docs for new K8s upgrade process

- sidebars.js
SC: https://app.shortcut.com/replicated/story/76117/move-annotations-and-cleaning-up-kubernetes-jobs-higher-up-in-toc
Moved Kubernetes Operators to higher level near bottom. Also created a new TOC category called "Managing Objects" and moved the Annotations and Cleaning Up Kubernetes Jobs under the new category.
Preview: https://deploy-preview-1127--replicated-docs-upgrade.netlify.app/
> 76117: Move Annotations, Kubernetes Jobs, and Kubernetes Objects in TOC

- docs/vendor/helm-install.md
Preview: https://deploy-preview-1136--replicated-docs-upgrade.netlify.app/vendor/helm-install#add-the-admin-console-chart
Adds a comment at the top of each code block to clarify which file it is
Adds header content to the top of each code block to clarify which file it is 
Cleans up the examples to make them consistent and reduce the overall length of the steps (each step has only one code block now).
> Add clarification between HelmChart and Helm chart files

- .github/workflows/app-manager-release-notes.yml
add k8s v1.27 for app manager release notes
SC - https://app.shortcut.com/replicated/story/74929/support-k8s-v1-27-1
> add k8s v1.27 for app manager release notes

- docs/partials/install/_kubernetes-compatibility.mdx
- docs/release-notes/rn-app-manager.md
- docs/vendor/policies-support-lifecycle.md
There is an issue with native Helm installs in KOTS on 1.27 - it will be resolved by the next patch release, but we should remove this support from docs until then
> remove k8s 1.27 support in KOTS

- docs/vendor/packaging-rbac.md
```
ethan@ethanm-okd-vagrant-2:~$ kubectl -n testing create -f role.yaml
role.rbac.authorization.k8s.io/kotsadm-role created
The RoleBinding "" is invalid: metadata.name: Required value: name or generateName is required
```
> fix: add kotsadm-rolebinding metadata name

- docs/reference/custom-resource-config.md
This PR fixes the examples used for repeatable config items.  Two issues were discovered when working on [SC-79625](https://app.shortcut.com/replicated/story/79625/repeatable-config-option-not-working-on-ui-cli):
1. The examples use a config item named `service_port`.  KOTS uses this item name to generate the name for the dynamic fields/resources.  This will result in an invalid resource that will be rejected by k8s because it has an underscore `_` in the name and does not conform to RFC 1123.
```
{"level":"info","ts":"2023-06-16T12:59:35Z","msg":"stderr (apply) = The Service \"nginx\" is invalid: \n* spec.ports[0].name: Invalid value: \"service_port-a1060f9b\": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an …
```
> fix variadic config examples and limitations

- docs/reference/template-functions-static-context.md
related to [sc-80547](https://app.shortcut.com/replicated/story/80547/replicated-release-lint-throw-an-helm-chart-missing-error-when-tlscert-return-empty-result-which-cause-chart-yaml-rendered)
> fix(TLSCert): clarify the nil should be ()

- docs/vendor/distributing-workflow.md
The broken link is [Managing Releases with the Vendor Portal](https://docs.replicated.com/vendor/releases-creating-release) in the table located in bullet 2, `Helm Charts` row.
https://docs.replicated.com/vendor/distributing-workflow#plan-promote-and-test-your-initial-release
> fix: correct a broken link in product docs

- docs/partials/linter-rules/_invalid-rendered-yaml.mdx
- docs/reference/linter.mdx
SC: https://app.shortcut.com/replicated/story/80217/kots-lint-returning-an-invalid-error-when-not-able-to-parse-helmchart-manifest
> add invalid-rendered-yaml lint docs

- docs/reference/replicated-sdk-apis.md
- docs/vendor/replicated-sdk-development.md
- docs/vendor/replicated-sdk-overview.md
feat: remove use of isRequired from sdk docs
sc: https://app.shortcut.com/replicated/story/80825/remove-use-of-required-releases-for-builders-plan
> feat: remove use of isRequired from sdk docs

- .gitignore
- docs/vendor/replicated-sdk-development.md
Visiting https://docs.replicated.com/vendor/replicated-sdk-development#initialize and clicking on [Replicated Helm Values](https://docs.replicated.com/vendor/helm-install#replicated-values) takes you to the wrong page
> chore: Fix broken link to reach Helm SDK Values

- docs/reference/custom-resource-config.md
This PR updates the config group name for the repeatable items examples so that it's clear that the group name should be used in the `valuesByGroup` field. Previously the name was `ports`, which also was the name of the yaml field that was being used as well, so the example was not immediately clear from the example that the key in `valuesByGroup` needs to match the parent group name (we do doc this [here](https://docs.replicated.com/reference/custom-resource-config#repeatable-items)).
> improve repeatable config items example

- docs/reference/replicated-cli-customer-ls.md
document new cli feature which lists customers and instances for a specific application version.
added a new flag for ls called --appversion
For example:
replicated customer ls --appversion 0.1.0
> document new cli feature which lists customers and instances for a specific application version

- docs/enterprise/updating-licenses.md
- docs/vendor/licenses-about-types.md
- docs/vendor/licenses-about.md
https://app.shortcut.com/replicated/story/82541/add-info-that-licenses-types-can-t-be-replaced
Previews:
- New section: https://deploy-preview-1273--replicated-docs-upgrade.netlify.app/vendor/licenses-about#updating-and-replacing-licenses
- Updated license types section: https://deploy-preview-1273--replicated-docs-upgrade.netlify.app/vendor/licenses-about#license-types
- Community license topic: https://deploy-preview-1273--replicated-docs-upgrade.netlify.app/vendor/licenses-about-types
> Clarify that users can't replace licenses

- docs/vendor/replicated-sdk-overview.md
SC: https://app.shortcut.com/replicated/story/83916/serve-cached-data-from-replicated-app
Preview: https://deploy-preview-1310--replicated-docs.netlify.app/vendor/replicated-sdk-overview#sdk-resiliency
> 83916: Served Cached Data for SDK

- docs/partials/instance-insights/_notifications-about.mdx
- docs/vendor/instance-notifications-config.mdx
- docs/vendor/team-management-slack-config.mdx
Related story: https://app.shortcut.com/replicated/story/83134/notifications-beta-remove-feature-flag-add-beta-label-in-product-update-docs
> change alpha to beta for notifications

- docs/vendor/team-management-rbac-resource-names.md
Related story: https://app.shortcut.com/replicated/story/83724/docs-list-license-id-in-rbac-docs-but-it-s-actually-customer-id
> change licenseId to customerId

- docs/vendor/replicated-onboarding.md
Reverting this name change from replicated to replicated-sdk. Will be updated instead as part of this PR, which is holding for a vendor portal release: https://github.com/replicatedhq/replicated-docs/pull/1314
> Revert name update for replicated sdk

- docs/vendor/replicated-onboarding.md
Now that https://github.com/replicatedhq/replicated-docs/pull/1314 is merged, need to update the SDK name to match the new name
> Update sdk name

- .github/workflows/replicated-sdk-release-notes.yml
- docs/release-notes/rn-replicated-sdk.md
- sidebars.js
[SC-83240](https://app.shortcut.com/replicated/story/83240/create-release-notes-for-the-sdk)
This PR:
- adds a page for the Replicated-SDK release notes.
- adds `replicated-sdk-release-notes` workflow to open a PR to update the release notes when there is a new version of the SDK released.
Adding the replicated sdk release notes to the sidebar will be part of a different PR: https://github.com/replicatedhq/replicated-docs/pull/1344
This is so that this workflow can be merged and tested before the page is visible in our docs site.
> SDK release notes

- docs/partials/config/_affixExample.mdx
- docs/reference/custom-resource-config.md
- docs/vendor/admin-console-customize-config-screen.md
SC: https://app.shortcut.com/replicated/story/83756/affix-parameter-in-kots-config-needs-to-be-set-on-all-objects-in-a-group-otherwise-it-doesn-t-get-applied
Previews:
- https://deploy-preview-1339--replicated-docs.netlify.app/reference/custom-resource-config#affix
- https://deploy-preview-1339--replicated-docs.netlify.app/vendor/admin-console-customize-config-screen#add-fields-to-the-configuration-screen
> 83756: Clarify affix field settings

- .github/workflows/replicated-sdk-release-notes.yml
This PR modifies the release notes workflow for the replicated-sdk:
- passes the previous tag in the repo to the release notes generator to use as the base.
> pass previous tag as base to release notes generator

- docs/release-notes/rn-replicated-sdk.md
- sidebars.js
- src/css/custom.css
This PR: 
- adds the replicated sdk release notes page to the sidebar so that they are visible in `docs.replicated.com`
- includes a note about the breaking change in the beta release
> add replicated sdk release notes to sidebar

- docs/reference/replicated-cli-cluster-create.md
- docs/vendor/testing-replicated-instance-types.md
- docs/vendor/testing-supported-clusters.md
- sidebars.js
Moving VM based Compatibility Matrix instances from VCPUs and Memory to instance types.
> HOLD FOR RELEASE - Document replicated instance types for VMs

- src/css/custom.css
I used this Coolers color palette generator using the three existing colors for the New Features, Improvements, and Bug Fixes labels.  https://coolors.co/palette/f47878-38c1ca-4bc99c-e65dad-414288
You can play around with palettes by "locking" the red, blue, and green color here, then pressing the space bar to get more suggestions for the other two colors: https://coolors.co/f47878-38c1ca-4bc99c-e65dad-414288
Note: I had added a label for breaking changes in this PR https://github.com/replicatedhq/replicated-docs/pull/1344/files#diff-44813f307e729042af7e70beff6f32ea63a7941bc100043a49e84d229ea2570f
> Add release note label for known issues

- docs/reference/custom-resource-config.md
I think the release notes is the only place that mentions when support for regex validation was added to KOTS.  If a user is starting from this page, they wouldn't likely come across that information and will think it just doesn't work.
> add kots version for regex validation

- docs/reference/replicated-sdk-apis.md
SC: https://app.shortcut.com/replicated/story/81257/add-samples-responses-to-the-mock-data-api-reference
The scope of this SC has changed - the mock data endpoints need to be removed from the docs.
> 81257: Remove Mock Data Endpoints

- docs/partials/config/_property-when.mdx
SC: https://app.shortcut.com/replicated/story/80224/replicated-docs-for-when-and-select-one-are-misleading
Preview: https://deploy-preview-1373--replicated-docs-upgrade.netlify.app/reference/custom-resource-config#when
> 80224: Clarify `when` and `select_one` config usage

- docs/partials/replicated-sdk/_overview.mdx
- docs/vendor/insights-app-status.md
- docs/vendor/install-with-helm.md
- docs/vendor/replicated-sdk-overview.md
New Limitations section in About the Replicated SDK topic: https://deploy-preview-1419--replicated-docs.netlify.app/vendor/replicated-sdk-overview#limitations
Updated the "Enabling and Understanding Application Status" topic to explain the different requirements depending on Helm install method: https://deploy-preview-1419--replicated-docs.netlify.app/vendor/insights-app-status#helm-installations
I also made a handful of semi-related editorial updates that are explained further in the comments 🙂
> Add info about custom status informer requirements

- docs/enterprise/snapshots-troubleshooting-backup-restore.md
This PR is a result of some recent support escalations where snapshots failed because of the node-agent memory limit.  This is documented as a known issue here, but the goal is to make it more discoverable and add some additional details to that users can more easily identify this as the issue.
Changes:
* Moved the "Snapshot Creation is Failing" section ahead of the "Snapshot Restore is Failing" section
* Added an example of what an error might look like when a backup fails due to this memory limit being hit
* Added example commands to patch the node-agent (restic) daemonset memory limit
> reorganize and add details to node-agent memory limit section

- docs/enterprise/snapshots-creating.md
- docs/partials/linter-rules/_linter-definition.mdx
- docs/reference/cron-expressions.md
- docs/reference/custom-resource-about.md
- docs/reference/custom-resource-backup.md
- docs/reference/custom-resource-preflight.md
- docs/reference/custom-resource-redactor.md
- docs/reference/custom-resource-sig-application.md
- docs/reference/linter.mdx
- docs/vendor/admin-console-adding-buttons-links.md
- docs/vendor/releases-creating-cli.mdx
- docs/vendor/releases-creating-customer.md
- docs/vendor/snapshots-configuring-backups.md
- docs/vendor/tutorial-ui-create-release.md
- netlify.toml
- sidebars.js
Changes:
- KOTS Custom Resources and Template Functions are top-level in the KOTS sidebar (rather than being nested under Reference section)
- Removed that References bucket all together and redistributed the other topics that were there:
- Cron Expressions topic is moved to the "Install and Manage" section in the KOTS sidebar since enterprise customers are the ones who would need that info when configuring auto updates or backups
- Linter Rules is moved to Channel and Release Management section in the main sidebar
- The Velero Backup custom resource was moved to Backup and Restore section in the KOTS sidebar (so that only the kots.io custom resources are under Custom Resources)
- Remove the SIG Application custom resource topic as it was only about 3 sentence long. Condense the info into …
> Bring CRs up one level in KOTS sidebar

- docs/enterprise/installing-general-requirements.mdx
- docs/vendor/packaging-rbac.md
Added _About Installing with Minimal RBAC_ section to the vendor topic about Configuring KOTS RBAC: https://deploy-preview-1460--replicated-docs.netlify.app/vendor/packaging-rbac#about-installing-with-minimal-rbac
Added additional step in the minimal rbac procedure for adding any CRDs to the Role that you create: https://deploy-preview-1460--replicated-docs.netlify.app/enterprise/installing-general-requirements#namespace-scoped
> 89383: Update KOTS Minimal RBAC docs

- docs/enterprise/updating-patching-with-kustomize.md
Starting Kustomize 5 (which is the version of Kustomize that recent KOTS versions adopted), there was a breaking change introduced to the use of `patches`. More details: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0
> Drop support for a very old, legacy style of patches. patches used to be allowed to be used as an alias for patchesStrategicMerge in kustomize v3. You now have to use patchesStrategicMerge explicitly, or update to the new syntax supported by patches
This PR updates the syntax to accommodate those changes.
> Update syntax for using kustomize patches

- docs/vendor/team-management-rbac-resource-names.md
Related to [this support issue](https://github.com/replicated-collab/git-guardian-kots/issues/140) - found an RBAC resource we didn't have documented yet for archiving a channel.
> add channel archive RBAC resource

- docs/partials/replicated-sdk/_dependency-yaml.mdx
Bumps the SDK version reference to the latest `1.0.0-beta.10`
> sdk 1.0.0-beta.10

- docs/enterprise/delete-admin-console.md
- docs/release-notes/rn-kubernetes-installer.md
Update `Resetting a node` hyperlink found https://docs.replicated.com/enterprise/delete-admin-console#delete-the-admin-console and in several other places in the docs
> Update kURL node reset hyperlinks

- docs/enterprise/snapshots-troubleshooting-backup-restore.md
- docs/enterprise/snapshots-understanding.md
Updates Velero version compatibility table to reflect support for the latest version 1.12.1.
Also updates, the troubleshooting topic to indicate that the issue in 1.10.3 and 1.11.0 has been resolved more recent releases.
> update velero compatibility

- docs/vendor/testing-supported-clusters.md
OpenShift prior to 4.13 does not implement a registry mirror, this change adds a note to limitations to highlight that the vendor needs to implement an image pull secret to overcome rate limiting from Dockerhub.
> Chore: CMX - add note about dockerhub pull secret requirement

- docs/vendor/helm-native-v2-using.md
- docs/vendor/helm-v2-migrate.md
- sidebars.js
Update the headings of the existing Configuring topic and remove the information that is specific to migrating existing installations: https://deploy-preview-1616--replicated-docs.netlify.app/vendor/helm-native-v2-using
Moved the info about migrating existing installations to a new topic: https://deploy-preview-1616--replicated-docs.netlify.app/vendor/helm-v2-migrate
> Clarify configuring and migrating  HelmChart CR

- docs/enterprise/snapshots-troubleshooting-backup-restore.md
[SC-93444](https://app.shortcut.com/replicated/story/93444/velero-1-12-x-fail-to-update-the-storage-destination-velero-node-agent-keep-crashing-or-waiting)
This PR documents a known issue in Velero 1.12.0 and 1.12.1 in the "Troubleshooting Backup and Restore" section of the docs.
> add troubleshooting step for node-agent crashing

- README.md
- docs/vendor/policies-vulnerability-patch.md
The email address support@replicated.com, and Zendesk, have been unavailable and unmonitored for over a year.  This change removes references to those.
> remove references to obsolete support email

- docs/release-notes/rn-kubernetes-installer.md
An Oct release note was missing a # throwing off the formatting style
> Fix formatting issue

- docs/partials/replicated-sdk/_dependency-yaml.mdx
bumps SDK version in the docs to the latest `1.0.0-beta.13`
> bump sdk version to 1.0.0-beta.13

- .github/workflows/app-manager-release-notes.yml
Updates the KOTS automated release notes workflow to indicate support for Kubernetes 1.29
> update KOTS release notes workflow for k8s 1.29

- docusaurus.config.js
- static/js/qualified.js
Docusaurus docs on the scripts property: https://docusaurus.io/docs/api/docusaurus-config#scripts
Related stackoverflow: https://stackoverflow.com/questions/57859350/how-can-i-add-custom-scripts-in-index-htmls-head-part-in-docusaurus-v2
Here's where the feature was added in docusauurs v2: https://github.com/facebook/docusaurus/pull/1831
> Add qualified scripts

- docs/vendor/replicated-sdk-overview.md
This PR adds a known limitation for KOTS applications that include the Replicated SDK.
This is a documentation change ahead of fixing a known issue as part of https://app.shortcut.com/replicated/story/98631/special-yaml-characters-in-license-field-titles-cause-kots-to-fail-when-configuring-the-sdk
> add known SDK limitation for license fields

- docs/partials/replicated-sdk/_401-unauthorized.mdx
- docs/partials/replicated-sdk/_kots-version-req.mdx
- docs/partials/replicated-sdk/_registry-logout.mdx
- docs/vendor/helm-install-release.md
- docs/vendor/replicated-sdk-installing.md
- docs/vendor/tutorial-config-package-chart.md
- docs/vendor/tutorial-kots-helm-package-chart.md
Added a registry logout step to:
* Installing the SDK: https://deploy-preview-2002--replicated-docs.netlify.app/vendor/replicated-sdk-installing#install-the-sdk-as-a-subchart
* Packaging a Helm Chart: https://deploy-preview-2002--replicated-docs.netlify.app/vendor/helm-install-release#release
Also added a note to a couple tutorials that ask users to package a Helm chart w/ the SDK in case they run into the 401 error there. Example: https://deploy-preview-2002--replicated-docs.netlify.app/vendor/tutorial-kots-helm-package-chart
> Add registry logout step

- docs/reference/replicated-cli-customer-create.md
- docs/reference/replicated-cli-customer-ls.md
- docs/reference/replicated-cli-registry-add-gar.mdx
- docs/reference/replicated-cli-registry-add.mdx
- sidebars.js
* Add Google Artifact Registry to `replicated registry add` command
- Google Artifact Registry supports both service account and OAuth  token based authentication
* Updated docs for creating new customers with `--custom-id my-salesforce-id` parameter
- Updates `replicated customer ls` to display new `CUSTOM_ID` column
> Add Google Artifact Registry and custom-id

- docs/vendor/policies-infrastructure-and-subprocessors.md
Both vendors were previously approved, but mistakenly left out from the list.
> Added Postmark and Active Campaign.

- docs/enterprise/installing-general-requirements.md
Since `1.17`, the ports for the `kube-controller-manager` and `kube-scheduler` have changed. See - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#cluster-lifecycle-1
Upstream docs - https://kubernetes.io/docs/reference/networking/ports-and-protocols/
> Update ports in systems requirements 

- docs/vendor/replicated-onboarding.md
Minor typo: `command to to create`
> Fix typo in replicated-onboarding.md

- docs/reference/custom-resource-config.mdx
The `heading` config item type works as expected in KOTS. Removing this note as it was carried over from the legacy docs site and doesn't really make sense.
```
- name: some_heading
type: heading
title: Heading Example
```
> removes note about unsupported heading config item

- docs/vendor/instance-insights-details.md
Related SC story: https://app.shortcut.com/replicated/story/101882/add-docs-and-remove-feature-flag-for-granular-app-status
Preview:
- [Current state section](https://deploy-preview-2203--replicated-docs.netlify.app/vendor/instance-insights-details#current-state)
- [Instance activity section](https://deploy-preview-2203--replicated-docs.netlify.app/vendor/instance-insights-details#app-status)
> [HOLD FOR MERGE] Add granular app status to docs

- docs/reference/replicated-sdk-apis.md
Add descriptions of the new `/app/instance-tags` endpoint on Replicated SDK
> Replicated SDK instance-tags API

- docs/reference/replicated-sdk-apis.md
A stray comma makes JSON invalid.
> Fix syntax error in an example

- docs/reference/template-functions-about.mdx
Updates the Static Context description to be more clear about when in the application lifecycle they are available. In the case of Static template functions, they are _always_ available. The previous wording made it sound like they could be _used_ anywhere, which is not accurate since certain fields of KOTS custom resources do not support template functions.
> update static context description

- docs/reference/custom-resource-helmchart-v2.mdx
The `builder` field lacked an intro line that said it's for providing Helm values. I also updated a paragraph that didn't make sense. I think this is what it was trying to say…
> Update builder field

- docs/reference/embedded-config.mdx
- docs/vendor/embedded-overview.mdx
I figure we won't always keep these up to date, so I added another note about the EC releases page in GitHub. I just noticed that this is different than the wording used on the EC config page, so we could make those the same if you want. I'm obviously fine if you change the wording or the link formatting.
> Update EC version

- .github/workflows/app-manager-release-notes.yml
updates the release notes automation for KOTS to drop stated support for 1.26 and add 1.30
> update kots automated release notes k8s compatibility

- docs/reference/embedded-config.mdx
- docs/vendor/embedded-overview.mdx
document the `builtInExtensions` part of the embedded cluster configuration.
> HOLD FOR RELEASE: document builtInExtensions section for embedded cluster

- docs/reference/embedded-config.mdx
TL;DR
-----
Makes our example Helm extension work with airgap
Details
-------
Adds some values to the example configuration for the NGINX ingress
controller so that it works with our current airgap implementation.
There's a comment on the example to explain why the values need to
be set, which should help since they're set blanks to avoid the
defaults in the NGINX Ingress Controller chart.
I'm not sure the timeline for fixing the limitation of the airgap
builder where it doesn't handle multi-architecture images correctly. We
should coordinate this with @ajp-io to assure the example is updated
when the builder knows what to do with those images.
> Updates Helm extension example for airgap

- docs/vendor/packaging-private-images.md
the correct role is Artifact Registry Reader, not Storage Object Viewer
> update role requirements for GAR private repos

- docs/vendor/tutorial-embedded-cluster-install.mdx
We stopped enabling the DR entitlement by default when you enable EC, so Velero won't get deployed in this tutorial now.
> Don't show Velero in tutorial

- docs/partials/kots-cli/_strict-sec-context-yaml.mdx
- docs/partials/kots-cli/_strict-security-context.mdx
- docs/reference/kots-cli-admin-console-generate-manifests.mdx
- sidebars.js
https://deploy-preview-2492--replicated-docs-upgrade.netlify.app/reference/kots-cli-admin-console-generate-manifests
> Add KOTS security context

- docs/enterprise/installing-embedded-air-gap.mdx
- docs/partials/embedded-cluster/_update-air-gap-admin-console.mdx
- docs/partials/embedded-cluster/_update-air-gap-cli.mdx
We added `-f` to the command so that it will show the HTTP status code if the command fails.
Could update screenshots but nbd for something like this.
> Add -f to EC curl command

- docs/partials/config/_item-types.mdx
- docs/partials/config/_whenExample.mdx
- docs/partials/configValues/_selectOneExample.mdx
- docs/partials/template-functions/_ne-comparison.mdx
- docs/reference/custom-resource-config.mdx
- docs/reference/template-functions-examples.mdx
- docs/vendor/config-screen-conditional.mdx
- docs/vendor/helm-optional-charts.md
- docs/vendor/releases-configvalues.md
- docs/vendor/tutorial-adding-db-config.md
- [dropdown](https://deploy-preview-2564--replicated-docs-upgrade.netlify.app/reference/custom-resource-config#dropdown)
- [radio](https://deploy-preview-2564--replicated-docs-upgrade.netlify.app/reference/custom-resource-config#radio)
- Marked select_one as deprecated: https://deploy-preview-2564--replicated-docs-upgrade.netlify.app/reference/custom-resource-config#select_one-deprecated
- Updated various examples to use radio instead of select_one. For example: https://deploy-preview-2564--replicated-docs-upgrade.netlify.app/vendor/config-screen-conditional#embedded-cluster-distribution-check and https://deploy-preview-2564--replicated-docs-upgrade.netlify.app/reference/template-functions-examples#boolean-comparison
> Doc radio and dropdown item types for config

- docs/vendor/embedded-overview.mdx
Kubernetes actually supports upgrading by up to 3 minor versions as of 1.28. Given that we only support two minor versions right now, and we intend to add some blocking that will prevent people from upgrading by more than 3 minor versions, this limitation isn't relevant, at least not for now.
> Remove K8s upgrade limitation

- docs/reference/embedded-config.mdx
- docs/reference/template-functions-about.mdx
- docs/vendor/embedded-overview.mdx
* Added to the bottom of the main list of Limitations: https://deploy-preview-2583--replicated-docs-upgrade.netlify.app/vendor/embedded-overview#limitations
* Added new Limitations section in the Embedded Cluster Config topic: https://deploy-preview-2583--replicated-docs-upgrade.netlify.app/reference/embedded-config#limitations
* Added the limitation to the About Template Functions topic as well: https://deploy-preview-2583--replicated-docs-upgrade.netlify.app/reference/template-functions-about#limitations
> Clarify EC template func limitation

- docs/vendor/ci-overview.md
- docs/vendor/ci-workflows.mdx
- docs/vendor/team-management-rbac-configuring.md
Updated labels for the existing examples in the Configuring RBAC topic: https://deploy-preview-2620--replicated-docs.netlify.app/vendor/team-management-rbac-configuring#example-no-access-to-stable-channel
"About Creating RBAC Policies for CI/CD" in CI/CD example workflows: https://deploy-preview-2620--replicated-docs.netlify.app/vendor/ci-workflows#about-creating-rbac-policies-for-cicd
CI/CD best practices: https://deploy-preview-2620--replicated-docs.netlify.app/vendor/ci-overview#best-practices-and-recommendations
> Add info about RBAC policies for CI

- docs/vendor/replicated-sdk-customizing.md
Adding docs for this change: https://github.com/replicatedhq/replicated-sdk/pull/209
> Document custom CA use with replicated SDK

- docs/reference/kots-cli-admin-console-generate-manifests.mdx
- docs/reference/kots-cli-install.mdx
- docs/reference/kots-cli-pull.md
The capitalization and periods at the end are not consistent, so I tried to match what each page had
> Document --private-ca-configmap flags

- package.json
- yarn.lock
Removes this warning when you run `yarn start`:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
> Update browser list

- yarn.lock
Fixes ~15 vulns in various npm modules. Because we deploy a static site, none were reachable, but its nice to have our env clean of any known vulns any way.
npm audit still reports some known vulns, but are either unreachable or unfixable at this time.
> upgrades for vuln fixes

- docs/vendor/private-images-replicated.mdx
Because we've decided not to address a fix, we need to reposition the 2gb layer from a known issue to a limitation.
> Reposition the 2gb layer from a known issue to a limitation

- docs/enterprise/installing-kurl-airgap.mdx
- docs/enterprise/installing-kurl.mdx
- docs/partials/install/_embedded-ha-step.mdx
- docs/partials/install/_ha-load-balancer-prereq.mdx
Online: https://deploy-preview-2720--replicated-docs.netlify.app/enterprise/installing-kurl#prerequisites
Air gap: https://deploy-preview-2720--replicated-docs.netlify.app/enterprise/installing-kurl-airgap#prerequisites
> Edit HA mode info in kurl install docs

- docs/reference/custom-resource-config.mdx
Feel free to word this differently as needed
> Note repeatable items Helm limitation

- .github/workflows/replicated-sdk-release-notes.yml
- docs/reference/template-functions-examples.mdx
Replicated SDK releases will no longer use `v` prefix in version tags
> HOLD FOR RELEASE: Replicated SDK no longer uses v to prefix versions

- docs/vendor/releases-share-download-portal.md
This comes from a question a vendor posed here: https://github.com/replicated-collab/grammatech-replicated/issues/50#issuecomment-2405787343
I'm open to better ways to present/phrase this. Wasn't sure exactly where to put it.
> Add documentation for download portal session length

- docs/vendor/replicated-sdk-customizing.md
Relevant PR: https://github.com/replicatedhq/replicated-sdk/pull/215
Rendered preview:
> Docs for using Secret to store custom CA

- docs/partials/replicated-sdk/_dependency-yaml.mdx
- docs/release-notes/rn-replicated-sdk.md
- docs/vendor/replicated-sdk-customizing.md
- docs/vendor/replicated-sdk-installing.mdx
Release https://github.com/replicatedhq/replicated-sdk/releases/tag/1.0.0-beta.31
> Release notes for SDK 1.0.0-beta.31 plus related docs

- docs/vendor/testing-supported-clusters.md
The current link to "creating a kURL installer" doesn't actually help me find the info I need. I need the kURL installer ID slug. Outside of trying to use kURL.sh to get this ID, I need to go find it in my installers history. Still not the easiest to discover ,but a small improvement towards pointing me in the right direction. 
I'm not sure if this page is deep linkable or not since it's context specific, but this is an example of what the URL for the right page looks like https://vendor.replicated.com/apps/{app-id}/channels/{channel-id)/kubernetes-installers?page=0
> Update kURL to clarify version expectation

- docs/vendor/helm-packaging-airgap-bundles.mdx
Story : https://app.shortcut.com/replicated/story/114703/documentation-fixes-in-helm-packaging-airgap-bundles-mdx
Made few doc corrections as per the story. Also, requesting the doc team to review full section to verify if any other changes are required.
> Corrected typos in helm-packaging-airgap-bundles section

- docs/reference/replicated-cli-cluster-shell.mdx
- docs/vendor/testing-how-to.md
- sidebars.js
New `cluster shell` reference topic: https://deploy-preview-2784--replicated-docs-upgrade.netlify.app/reference/replicated-cli-cluster-shell
Updated the "Access Cluster" steps to describe using `cluster shell` instead of `cluster kubeconfig`: https://deploy-preview-2784--replicated-docs-upgrade.netlify.app/vendor/testing-how-to#access-clusters
Note: The `cluster kubeconfig` method of accessing clusters is still referenced in the CI/CD topics: https://docs.replicated.com/vendor/ci-workflows
> add `cluster shell` doc page

- docs/reference/embedded-cluster-install.mdx
https://deploy-preview-2798--replicated-docs.netlify.app/reference/embedded-cluster-install
> Add missing install flags

- docs/vendor/embedded-overview.mdx
TL;DR
-----
Documents limitation on policy enforcement
Details
-------
This change documents that Embedded Cluster does not support enforcing policy on the workloads run by the embedded cluster. This may not be a common use case, so it may not make sense to add this change. I'm suggesting it and asking @ajp-io and @chris-sanders to take a look.
> Documents limitation on policy enforcement

- docs/reference/cron-expressions.md
https://deploy-preview-2811--replicated-docs-upgrade.netlify.app/reference/cron-expressions
> Remove unsupported special characters

- docs/enterprise/installing-embedded-air-gap.mdx
- docs/enterprise/installing-embedded.mdx
- docs/partials/embedded-cluster/_ec-config.mdx
- docs/partials/getting-started/_gitea-ec-config.mdx
- docs/reference/embedded-config.mdx
- docs/vendor/quick-start.mdx
Updated install instructions: https://deploy-preview-2809--replicated-docs-upgrade.netlify.app/enterprise/installing-embedded#install (also copied the same steps to the air gap install topic)
Updated the quick start flow (note that the sample app does not have a config nor preflights): https://deploy-preview-2809--replicated-docs.netlify.app/vendor/quick-start#quick-start
> Updating EC install experience in Admin Console

- docs/vendor/team-management-rbac-resource-names.md
Related to https://app.shortcut.com/replicated/story/116067/backend-for-license-policies, add's two new RBAC resource names.
> Document new rbac license field override resources

- docs/vendor/licenses-install-types.mdx
> kots.io/installer-only docs

- docs/partials/helm/_helm-install-prereqs.mdx
- docs/partials/helm/_installer-only-annotation.mdx
- docs/vendor/licenses-install-types.mdx
Updated the requirements for the Helm install type to include the annotation YAML sample in the cell of the table: https://deploy-preview-2869--replicated-docs.netlify.app/vendor/licenses-install-types#install-types
> Update info about installer-only annotation

- docs/partials/replicated-sdk/_overview.mdx
And fix a typo
https://github.com/replicatedhq/replicated-docs/issues/2870
> Remove redundant bullet point

- docs/reference/replicated-sdk-apis.md
https://deploy-preview-2875--replicated-docs.netlify.app/reference/replicated-sdk-apis#use-port-forwarding-to-access-the-sdk-api
> Use port forward to access the SDK API

- docs/vendor/replicated-sdk-overview.md
Removing changes added in https://github.com/replicatedhq/replicated-docs/pull/1987. This issue has been resolved now.
Relevant story: https://app.shortcut.com/replicated/story/98631/special-yaml-characters-in-license-field-titles-cause-kots-to-fail-when-configuring-the-sdk
> Removing a limitation that has been resolved

- docs/vendor/replicated-sdk-customizing.md
Docs for the Affinity feature in Replicated SDK: https://github.com/replicatedhq/replicated-sdk/pull/227
> Docs for Replicated SDK affinity spec

- docs/release-notes/rn-replicated-sdk.md
Release notes for Replicated SDK 1.0.0-beta.33 https://github.com/replicatedhq/replicated-sdk/compare/1.0.0-beta.32...28a6f55
> Release notes for SDK 1.0.0-beta.33

- docs/reference/replicated-sdk-apis.md
https://app.shortcut.com/replicated/story/117902/document-replicated-sdk-s-integration-api
> Integration API docs

- package.json
- yarn.lock
Update various dependencies to fix security issues. including
- "immer": "^9.0.6",
- "loader-utils": "^2.0.3",
- "shell-quote": "^1.7.3"
> Update packages with critical security dependencies

- docs/partials/replicated-sdk/_registry-logout.mdx
- docs/vendor/helm-install-release.md
- docs/vendor/replicated-sdk-installing.mdx
Added a new Troubleshoot section in the installing the SDK topic to explain the helm dependency update error: https://deploy-preview-2918--replicated-docs.netlify.app/vendor/replicated-sdk-installing#troubleshoot
Also reformatted the info about `helm registry logout` info in the procedures themselves so that it's a note rather than a step:
> Add troubleshooting info for helm dependency update 401 errors

- docs/reference/custom-resource-backup.md
This doesn't actually work when it comes time to restore
> Remove orLabelSelectors support

- docs/reference/replicated-cli-cluster-create.md
This PR documents flags associated with the new `--addon` flag within the `replicated cluster create` command https://app.shortcut.com/replicated/story/107825
> Document replicated cluster create --addon flags

- docs/enterprise/installing-general-requirements.mdx
- docs/enterprise/installing-overview.md
- docs/enterprise/installing-stateful-component-requirements.md
- docs/vendor/packaging-air-gap-excluding-minio.md
https://deploy-preview-2963--replicated-docs-upgrade.netlify.app/enterprise/installing-stateful-component-requirements
* Removed kurl info from the installing without object storage topic (confirmed that the relevant info for kurl installs is in the kurl "selecting storage add-ons" topic)
* Updated the title to clarify that it's for installing kots in existing clusters
* Updated xrefs accordingly
> Remove kurl info from installing without object storage topic

- docs/partials/embedded-cluster/_port-reqs.mdx
https://deploy-preview-2968--replicated-docs.netlify.app/enterprise/installing-embedded-requirements#port-requirements
> Update port requirements for EC

- docs/enterprise/image-registry-kurl.md
- docs/enterprise/image-registry-settings.mdx
- docs/enterprise/installing-general-requirements.mdx
- docs/reference/custom-resource-helmchart-v2.mdx
- docs/vendor/helm-native-v2-using.md
- sidebars.js
https://deploy-preview-2905--replicated-docs-upgrade.netlify.app/enterprise/image-registry-settings
> Clarify supported install types for using local image registries

- docs/partials/embedded-cluster/_kurl-comparison.mdx
- docs/vendor/embedded-overview.mdx
https://deploy-preview-2994--replicated-docs.netlify.app/vendor/embedded-overview#comparison-to-kurl
> Explain EC built-in extensions in contrast to kurl

- docs/enterprise/embedded-manage-nodes.mdx
- docs/partials/embedded-cluster/_requirements.mdx
- docs/reference/embedded-cluster-install.mdx
data-dir flag limitations: https://deploy-preview-3031--replicated-docs.netlify.app/reference/embedded-cluster-install#flags
Multi-node limitations: https://deploy-preview-3031--replicated-docs.netlify.app/enterprise/embedded-manage-nodes#limitations
> Add limitation related to setting data dir when joining nodes

- docs/vendor/embedded-overview.mdx
i'm open to any wording changes. this sentence seems straightforward already, but i've seen more than one vendor think they can't use templating if they use EC
> clarify that you can template files other than EC Config

- docs/release-notes/rn-embedded-cluster.md
https://github.com/replicatedhq/embedded-cluster/compare/1.22.0+k8s-1.30...2.0.0+k8s-1.30
https://github.com/replicatedhq/kots/compare/v1.124.0...v1.124.3
> feat(ec): release 2.0.0

- docs/vendor/custom-domains-using.md
* Follow-up from [SC-115604](https://app.shortcut.com/replicated/story/115604/support-for-caa-record-in-dns-to-limit-cert-authority)
* Updates notice about CAA records and lists CAs to add
* This method has been tested and appears to work
> Update info for CAAs in Configure a Custom Domain section

- docs/release-notes/rn-replicated-sdk.md
- docs/vendor/replicated-sdk-customizing.md
https://deploy-preview-3089--replicated-docs.netlify.app/vendor/replicated-sdk-customizing#add-custom-labels
> Add docs for podLabels and commonLabels for SDK 

- docs/partials/template-functions/_config-context.mdx
- docs/partials/template-functions/_identity-context.mdx
- docs/partials/template-functions/_kurl-context.mdx
- docs/partials/template-functions/_license-context.mdx
- docs/partials/template-functions/_static-context.mdx
- docs/reference/template-functions-about.mdx
- docs/reference/template-functions-config-context.md
- docs/reference/template-functions-identity-context.md
- docs/reference/template-functions-kurl-context.md
- docs/reference/template-functions-license-context.md
- docs/reference/template-functions-static-context.md
https://deploy-preview-3097--replicated-docs.netlify.app/reference/template-functions-config-context
and 
https://deploy-preview-3097--replicated-docs.netlify.app/reference/template-functions-about#contexts
> Add HelmChart examples to Config template func page

- docs/reference/embedded-config.mdx
- docs/vendor/custom-domains-using.md
- docs/vendor/custom-domains.md
- docs/vendor/embedded-overview.mdx
Embedded Cluster Config reference: https://deploy-preview-3116--replicated-docs.netlify.app/reference/embedded-config#domains
Configure EC to Use Custom Domains in _Using Custom Domains_: https://deploy-preview-3116--replicated-docs.netlify.app/vendor/custom-domains-using#ec
> HOLD FOR RELEASE Custom domains for EC

- docs/partials/custom-resource-application/_proxyRegistryDomain.mdx
- docs/partials/custom-resource-application/_replicatedRegistryDomain.mdx
- docs/vendor/helm-native-v2-using.md
I saw another site do this for custom domains, and I thought it made more sense than mycompany, which I previously wrote.
> change yourcompany to mycompany

- docs/reference/embedded-config.mdx
https://deploy-preview-3162--replicated-docs.netlify.app/reference/embedded-config#configure-kubelet-with-k0s-worker-profiles
> Document ability to configure workerProfiles

- docs/reference/embedded-config.mdx
> Don't use default for name

- docs/partials/replicated-sdk/_sdk-values.mdx
Fixing a dead link to https://github.com/replicatedhq/replicated-sdk/blob/main/chart/values.yaml
> Fixing a dead link in the SDK values page

- docs/reference/replicated-cli-installing.mdx
In the command to install replicated CLI, `curl` should be sufficient to download the binary. There is no need for having users have both in their environments
> chore: Remove need to have wget in install instructions

- docs/partials/embedded-cluster/_proxy-env-vars.mdx
- docs/reference/embedded-cluster-install.mdx
https://deploy-preview-3212--replicated-docs-upgrade.netlify.app/reference/embedded-cluster-install#flags
> HOLD FOR RELEASE: EC respects env vars for proxy installs

- docs/enterprise/embedded-manage-nodes.mdx
- docs/vendor/licenses-using-builtin-fields.mdx
https://deploy-preview-3214--replicated-docs.netlify.app/vendor/licenses-using-builtin-fields#install-options
https://deploy-preview-3214--replicated-docs.netlify.app/enterprise/embedded-manage-nodes#requirement
> HOLD FOR RELEASE: Add multi-node license option for embedded cluster

- docs/enterprise/embedded-manage-nodes.mdx
https://deploy-preview-3237--replicated-docs.netlify.app/enterprise/embedded-manage-nodes#automate-node-joins
> remove json example and edit tar file name

- docs/vendor/replicated-sdk-slsa-validating.md
update the replicated-sdk SLSA, SBOM verification documentation
> updates based on new replicated-sdk verification features

- .github/workflows/embedded-cluster-release-notes.yml
- docs/release-notes/rn-embedded-cluster.md
Example PR that's generated when this dispatch is triggered: https://github.com/replicatedhq/replicated-docs/pull/3246. I believe there are no release notes as the release notes generator does a diff between the current version and the last release version. 
The above PR was tested manually with a workflow dispatch on the `diamonwiggins/test-workflow-dispatch` branch with:
```
curl -X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer $GITHUB_TOKEN" \
https://api.github.com/repos/replicatedhq/replicated-docs/actions/workflows/embedded-cluster-release-notes.yml/dispatches \
-d '{
"ref": "diamonwiggins/test-workflow-dispatch",
"inputs": {
"version": "2.4.0+k8s-1.30" 
}
}'
```
https://github.com/replicatedhq/replicated-docs/blob/diamonwiggins/test-workflow-dispatch/.g …
> Add repository dispatch for EC release notes

- docs/partials/custom-resource-application/_excludedImages.mdx
- docs/reference/custom-resource-application.mdx
https://app.shortcut.com/replicated/story/119848/allow-excluding-images-from-airgap-builds
https://deploy-preview-3263--replicated-docs.netlify.app/reference/custom-resource-application#excludedimages
> add excludedImages docs and example of 'auto' from the Istio Gateway chart

- docs/partials/embedded-cluster/_port-reqs.mdx
- static/vendor/embedded-overview.md
Reverts replicatedhq/replicated-docs#3287
This is not true for k0s.
> Revert "ETCD port 2379 must be open between nodes"

- docs/release-notes/rn-embedded-cluster.md
Since we now support three versions, the version table has three columns and the last row needs to span all three columns
> Fixing minor layout glitch

- docs/vendor/compatibility-matrix-usage.md
After changes in https://github.com/replicatedhq/vandoor/pull/7513, the CMX history page can now show a `"Queued Timeout"` status, this provides documentation around this new status and how the CMX history page has been changed to now show clusters and VMs that may have this status in addition to `terminated`.
> Update CMX history info to discuss Queued Timeout status

- docs/release-notes/rn-replicated-sdk.md
also fix values links for the 1.5.0 release
> 1.6.0 release notes with 'tlsCertSecretName' link

- docs/vendor/testing-supported-clusters.md
This updates the support for RKE2, as of https://github.com/replicatedhq/vandoor/pull/7552 we are disabling multi-node in RKE2 until VXLAN arrives.  Once that rolls out we can revert this PR.
> chore(cmx): update support for rke2

- docs/vendor/team-management-rbac-resource-names.md
Add RBAC role definitions for three new enterprise portal related operations.
- Updating Install Options
- Deleting Install Options
- Deleting EP Service Accounts
> Add RBAC role entries for new Vendor API enterprise portal routes

- docs/vendor/replicated-sdk-customizing.md
Document what RBAC rules are actually required for the SDK to function
Also document the new `minimalRBAC` helm chart value and how it functions, complete with generated RBAC role examples
> Document the actual RBAC permissions required and the minimalRBAC helm chart value

- docs/partials/helm/_helm-install-prereqs.mdx
- docs/vendor/helm-install-airgap.mdx
* Removes a reference from back when it was behind a feature flag
* Mentions that the Air Gap option has to be selected as well
> Improve helm air gap instructions

- docs/vendor/replicated-sdk-customizing.md
https://deploy-preview-3338--replicated-docs.netlify.app/vendor/replicated-sdk-customizing#enable-ssl
> edit enable ssl for sdk steps

- docs/partials/helm/_helm-cr-weight.mdx
TL;DR
-----
Enhances the Helm chart weight documentation to provide better context
about how weight values affect installation order across different
Replicated deployment methods.
Details
--------
This documentation update clarifies the full impact of the `weight`
parameter in Helm charts across the Replicated ecosystem. Previously,
the documentation only explained how weight affects KOTS application
order, but didn't mention its relevance to the Enterprise Portal's
display of installation instructions.
The improved documentation now explicitly states that the weight
parameter is used not just by KOTS but also by the Replicated Enterprise
Portal to order charts in installation and update instructions. This
gives users a more complete understanding of how the weight parameter
influences …
> Updates Helm chart weight documentation

- docs/enterprise/installing-embedded-automation.mdx
Removed the procedure partial which was causing confusion on this page with both the mention of existing cluster installs and the reference to the kots cli procedure which vendors then expected to work with EC installs. 
I don't think it's really necessary to say how to scrape the UI for config on this page (only used to recreate an existing install). And I'd like to see that improved in EC so it's not UI-based for a headless install. If we find we do need to add that UI procedure back before then, we'll want to add just that relevant part back vs the whole partial previously there. 
related internal slack thread about changing this page: https://replicated.slack.com/archives/C0499EGNPNY/p1753456745585659
> reduce headless EC install docs confusion

- docs/vendor/testing-vm-create.md
Added support for Almalinux 9 and 10
Added limitation around using selinux
> Joshd/sc 127902/selinux document how to use autorelabel

- docs/vendor/insights-app-status.md
https://deploy-preview-3448--replicated-docs-upgrade.netlify.app/vendor/insights-app-status#helm-cli-installations
> clarify statusInformers field for sdk

- docs/partials/cmx/_instance-types.mdx
- docs/vendor/testing-ingress.md
- docs/vendor/testing-supported-clusters.md
- docs/vendor/testing-vm-create.md
- sidebars.js
https://deploy-preview-3445--replicated-docs.netlify.app/vendor/testing-vm-create#replicated-instance-types
> Make instance type info more discoverable

- docs/vendor/operator-defining-additional-images.mdx
- docs/vendor/packaging-private-images.md
- docs/vendor/private-images-about.md
https://github.com/replicatedhq/vandoor/pull/7797
> HOLD FOR RELEASE: scope registry to one or more apps

- docs/vendor/helm-image-registry.mdx
Addressing a question @grantmiller asked about whether we recommend using a Helper or not for image pull secrets.
> Documents helper for image pull secrets

- docs/vendor/team-management-rbac-resource-names.md
Adds missing CMX RBAC resource names
> docs: add missing CMX RBAC resources

- docs/enterprise/installing-embedded-automation.mdx
- docs/reference/embedded-cluster-install.mdx
https://deploy-preview-3512--replicated-docs.netlify.app/reference/embedded-cluster-install#flags
https://deploy-preview-3512--replicated-docs.netlify.app/enterprise/installing-embedded-automation#online-internet-connected-installation (and air gap section too)
> Doc --ignore-app-preflights, --tls-cert, --tls-key

- docs/vendor/licenses-adding-custom-fields.md
TL;DR
-----
Adds the new types of custom license fields
Details
-------
Updates the docs on custom license fields to include the "Password" and "Enum" types. Passwords are essentially strings that are considered sufficiently sensitive to be masked in the UI, while enums allow you to specify a list of options for the users to choose from.
Provides more description of each type by moving the list of types into its own section and putting the types in a table with the name, an explanation, and the type of widget used on the "Manage Customer" screen.
> Documents new custom field types
